#include "AnalysisEngine.h"
#include <cmath>
#include <algorithm>
namespace referencelab {
float AnalysisEngine::db(float v)noexcept{return juce::Decibels::gainToDecibels(juce::jmax(v,1.e-5f),-100.f);}float AnalysisEngine::lufs(double e)noexcept{return e>1.e-10?(float)(-0.691+10.0*std::log10(e)):-100.f;}int AnalysisEngine::binFor(float l)noexcept{return juce::jlimit(0,histogramBins-1,(int)std::floor((l+100.f)*10.f));}
void AnalysisEngine::configureKWeighting()noexcept{auto shelfDesign=[&](Biquad&b){constexpr double f=1681.974450955533,g=3.99984385397;const double A=std::pow(10.0,g/40.0);const double w=2.0*juce::MathConstants<double>::pi*f/rate;const double cosine=std::cos(w);const double sine=std::sin(w);const double alpha=sine*.5*std::sqrt(2.0);const double root=2.0*std::sqrt(A)*alpha;b.set(A*((A+1)+(A-1)*cosine+root),-2*A*((A-1)+(A+1)*cosine),A*((A+1)+(A-1)*cosine-root),(A+1)-(A-1)*cosine+root,2*((A-1)-(A+1)*cosine),(A+1)-(A-1)*cosine-root);};auto highPass=[&](Biquad&b){constexpr double f=38.13547087602444,q=.5003270373238773;const double w=2.0*juce::MathConstants<double>::pi*f/rate;const double cosine=std::cos(w);const double sine=std::sin(w);const double alpha=sine/(2*q);b.set((1+cosine)/2,-(1+cosine),(1+cosine)/2,1+alpha,-2*cosine,1-alpha);};for(int c=0;c<2;++c){shelfDesign(shelf[c]);highPass(rlb[c]);}}
void AnalysisEngine::prepare(double sr)noexcept{rate=sr>0?sr:44100.0;chunkTarget=juce::jmax(1,(int)std::round(rate*.1));configureKWeighting();doReset();}
void AnalysisEngine::doReset()noexcept{chunkEnergy=0;chunkSamples=chunkIndex=shortIndex=validChunks=historyCount=0;momentChunks.fill(0);shortChunks.fill(0);gateCounts.fill(0);shortCounts.fill(0);gateEnergy.fill(0);for(int c=0;c<2;++c){shelf[c].clear();rlb[c].clear();std::fill(std::begin(previous[c]),std::end(previous[c]),0.f);}peak.store(-100);truePeak.store(-100);rms.store(-100);crest.store(0);momentary.store(-100);shortTerm.store(-100);integrated.store(-100);dynamicRange.store(0);correlation.store(0);width.store(0);resetRequested.store(false);}
float AnalysisEngine::integratedFromGate()const noexcept{double absoluteEnergy=0;std::uint64_t absoluteCount=0;for(int i=binFor(-70.f);i<histogramBins;++i){absoluteEnergy+=gateEnergy[(size_t)i];absoluteCount+=gateCounts[(size_t)i];}if(!absoluteCount)return-100.f;const float preliminary=lufs(absoluteEnergy/(double)absoluteCount);const float threshold=juce::jmax(-70.f,preliminary-10.f);double gatedEnergy=0;std::uint64_t gatedCount=0;for(int i=binFor(threshold);i<histogramBins;++i){gatedEnergy+=gateEnergy[(size_t)i];gatedCount+=gateCounts[(size_t)i];}return gatedCount?lufs(gatedEnergy/(double)gatedCount):-100.f;}
float AnalysisEngine::loudnessRange(float integratedValue)const noexcept{const int first=binFor(juce::jmax(-70.f,integratedValue-20.f));std::uint64_t total=0;for(int i=first;i<histogramBins;++i)total+=shortCounts[(size_t)i];if(total<2)return 0;auto percentile=[&](double p){const std::uint64_t target=(std::uint64_t)std::ceil(total*p);std::uint64_t sum=0;for(int i=first;i<histogramBins;++i)if((sum+=shortCounts[(size_t)i])>=target)return -100.f+i*.1f;return 20.f;};return juce::jmax(0.f,percentile(.95)-percentile(.10));}
void AnalysisEngine::finishChunk()noexcept{const double e=chunkEnergy/juce::jmax(1,chunkSamples);momentChunks[(size_t)chunkIndex]=e;chunkIndex=(chunkIndex+1)%4;shortChunks[(size_t)shortIndex]=e;shortIndex=(shortIndex+1)%30;validChunks=juce::jmin(30,validChunks+1);chunkEnergy=0;chunkSamples=0;double momentE=0;double shortE=0;for(auto v:momentChunks)momentE+=v;momentE/=juce::jmin(4,validChunks);for(int i=0;i<validChunks;++i)shortE+=shortChunks[(size_t)i];shortE/=validChunks;const float momentL=lufs(momentE);const float shortL=lufs(shortE);momentary.store(momentL);shortTerm.store(shortL);if(validChunks>=4&&momentL>=-70.f){const int bin=binFor(momentL);++gateCounts[(size_t)bin];gateEnergy[(size_t)bin]+=momentE;}if(validChunks>=30&&shortL>=-70.f)++shortCounts[(size_t)binFor(shortL)];const float integratedValue=integratedFromGate();integrated.store(integratedValue);dynamicRange.store(loudnessRange(integratedValue));}
void AnalysisEngine::process(const juce::AudioBuffer<float>&b)noexcept{
    if(resetRequested.exchange(false))doReset();if(b.getNumChannels()==0||b.getNumSamples()==0)return;
    double sum=0,sumL=0,sumR=0,sumLR=0,sumMid=0,sumSide=0;float p=0,tp=0;
    for(int i=0;i<b.getNumSamples();++i){float values[2]{b.getSample(0,i),b.getNumChannels()>1?b.getSample(1,i):b.getSample(0,i)};p=juce::jmax(p,juce::jmax(std::abs(values[0]),std::abs(values[1])));for(int c=0;c<2;++c){auto*x=previous[c];x[0]=x[1];x[1]=x[2];x[2]=x[3];x[3]=values[c];if(historyCount>=3)for(int k=1;k<=4;++k){const float t=k*.25f;const float t2=t*t;const float t3=t2*t;const float cubic=.5f*((2*x[1])+(-x[0]+x[2])*t+(2*x[0]-5*x[1]+4*x[2]-x[3])*t2+(-x[0]+3*x[1]-3*x[2]+x[3])*t3);tp=juce::jmax(tp,std::abs(cubic));}}historyCount=juce::jmin(4,historyCount+1);const float l=values[0];const float r=values[1];sum+=.5*(l*l+r*r);sumL+=l*l;sumR+=r*r;sumLR+=l*r;const float m=.5f*(l+r);const float side=.5f*(l-r);sumMid+=m*m;sumSide+=side*side;const double kl=rlb[0].process(shelf[0].process(l));const double kr=rlb[1].process(shelf[1].process(r));chunkEnergy+=kl*kl+kr*kr;if(++chunkSamples>=chunkTarget)finishChunk();}
    const double n=(double)b.getNumSamples();const double rmsGain=std::sqrt(sum/n);const float peakValue=db(p);peak.store(peakValue);truePeak.store(db(juce::jmax(p,tp)));rms.store(db((float)rmsGain));crest.store(peakValue-db((float)rmsGain));const double denominator=std::sqrt(sumL*sumR);correlation.store(denominator>1e-12?(float)juce::jlimit(-1.0,1.0,sumLR/denominator):0.f);width.store((float)juce::jlimit(0.0,1.0,std::sqrt(sumSide/(sumMid+sumSide+1e-12))));
}
MeterSnapshot AnalysisEngine::snapshot()const noexcept{return{peak.load(),truePeak.load(),rms.load(),crest.load(),momentary.load(),shortTerm.load(),integrated.load(),dynamicRange.load(),correlation.load(),width.load()};}
}
