#include "CacheManager.h"
#include <algorithm>

namespace referencelab {
CacheManager::CacheManager(std::size_t bytes):maximum(juce::jmax<std::size_t>(16u*1024u*1024u,bytes)){}
CacheManager::~CacheManager(){pool.removeAllJobs(true,10000);cancelPendingUpdate();std::scoped_lock lock(mutex);completions.clear();}
std::string CacheManager::key(const juce::File&f){return f.getFullPathName().toLowerCase().toStdString();}
std::shared_ptr<ReferenceAudioData> CacheManager::decode(const juce::File&f,juce::String&error){juce::AudioFormatManager formats;formats.registerBasicFormats();std::unique_ptr<juce::AudioFormatReader>reader(formats.createReaderFor(f));if(!reader){error="Formato audio non supportato o file non valido";return{};}if(reader->lengthInSamples<=0||reader->lengthInSamples>std::numeric_limits<int>::max()){error="Durata file non supportata";return{};}auto data=std::make_shared<ReferenceAudioData>();data->sampleRate=reader->sampleRate;data->samples.setSize(2,(int)reader->lengthInSamples);if(!reader->read(&data->samples,0,data->samples.getNumSamples(),0,true,true)){error="Errore durante la decodifica";return{};}if(reader->numChannels==1)data->samples.copyFrom(1,0,data->samples,0,0,data->samples.getNumSamples());return data;}
void CacheManager::loadAsync(const juce::File&file,Callback callback){auto id=key(file);{std::scoped_lock lock(mutex);auto found=entries.find(id);if(found!=entries.end()&&found->second.modified==file.getLastModificationTime()){found->second.use=++counter;completions.push_back({file,found->second.data,{},std::move(callback)});triggerAsyncUpdate();return;}if(found!=entries.end()){current-=found->second.bytes;entries.erase(found);}states[id]=CacheState::loading;}pool.addJob([this,file,callback=std::move(callback)]()mutable{juce::String error;auto data=decode(file,error);{std::scoped_lock lock(mutex);completions.push_back({file,std::move(data),std::move(error),std::move(callback)});}triggerAsyncUpdate();});}
void CacheManager::handleAsyncUpdate(){std::list<Completion>ready;{std::scoped_lock lock(mutex);ready.splice(ready.end(),completions);}for(auto&c:ready){bool retained=false;{std::scoped_lock lock(mutex);auto id=key(c.file);if(c.data){if(auto old=entries.find(id);old!=entries.end()){current-=old->second.bytes;entries.erase(old);}auto bytes=c.data->bytes();entries[id]={c.data,c.file.getLastModificationTime(),bytes,++counter};current+=bytes;states[id]=CacheState::cached;evictLocked();retained=entries.contains(id);}else states[id]=CacheState::error;}if(c.callback)c.callback(std::move(c.data),c.error,retained);}}
void CacheManager::evictLocked(){while(current>maximum&&!entries.empty()){auto oldest=std::min_element(entries.begin(),entries.end(),[](auto&a,auto&b){return a.second.use<b.second.use;});current-=oldest->second.bytes;states[oldest->first]=CacheState::notLoaded;entries.erase(oldest);}}
void CacheManager::setMaximumBytes(std::size_t bytes){std::scoped_lock lock(mutex);maximum=juce::jmax<std::size_t>(16u*1024u*1024u,bytes);evictLocked();}
std::size_t CacheManager::getMaximumBytes()const{std::scoped_lock lock(mutex);return maximum;}std::size_t CacheManager::getCurrentBytes()const{std::scoped_lock lock(mutex);return current;}
CacheState CacheManager::getState(const juce::File&f)const{std::scoped_lock lock(mutex);auto it=states.find(key(f));return it==states.end()?CacheState::notLoaded:it->second;}
void CacheManager::clear(){std::scoped_lock lock(mutex);entries.clear();states.clear();current=0;}
}
