#include "ComparisonProcessor.h"
#include <cmath>
#include <complex>
namespace referencelab {
namespace {
enum class FilterType{highPass,lowPass,bandPass};
struct Coefficients{double b0=1,b1=0,b2=0,a1=0,a2=0;};
Coefficients design(FilterType type,float hz,float q,float gain,double sampleRate)noexcept{const auto rate=sampleRate>0?sampleRate:44100.0;const double w=2.0*juce::MathConstants<double>::pi*juce::jlimit(10.0,rate*.49,(double)hz)/rate;const double c=std::cos(w);const double sine=std::sin(w);const double alpha=sine/(2.0*juce::jmax(.1,(double)q));double b0=1,b1=0,b2=0,a0=1+alpha,a1=-2*c,a2=1-alpha;if(type==FilterType::highPass){b0=(1+c)/2;b1=-(1+c);b2=(1+c)/2;}else if(type==FilterType::lowPass){b0=(1-c)/2;b1=1-c;b2=(1-c)/2;}else{const double gainLinear=std::pow(10.0,gain/20.0);b0=alpha*gainLinear;b2=-alpha*gainLinear;}return{b0/a0,b1/a0,b2/a0,a1/a0,a2/a0};}
double magnitude(const Coefficients&c,float frequency,double sampleRate)noexcept{const auto rate=sampleRate>0?sampleRate:44100.0;const auto w=2.0*juce::MathConstants<double>::pi*juce::jlimit(10.0,rate*.49,(double)frequency)/rate;const auto z=std::exp(std::complex<double>(0,-w));return std::abs((c.b0+c.b1*z+c.b2*z*z)/(1.0+c.a1*z+c.a2*z*z));}
}
void ComparisonProcessor::prepare(double sr,int)noexcept{rate=sr>0?sr:44100.0;for(auto*c:{&mixChain,&referenceChain})for(auto&ch:c->channel){ch.hp1.reset();ch.hp2.reset();ch.bandPass.reset();ch.lp1.reset();ch.lp2.reset();}previousMode=targetMode=settings.mode;modeBlend=1.f;eqWet=settings.bypass?0.f:1.f;configureFilters();}
void ComparisonProcessor::update(const ComparisonSettings&s)noexcept{auto coefficientsChanged=s.highPassHz!=settings.highPassHz||s.bandPassHz!=settings.bandPassHz||s.bandPassGainDb!=settings.bandPassGainDb||s.bandPassQ!=settings.bandPassQ||s.lowPassHz!=settings.lowPassHz;if(s.mode!=targetMode){previousMode=targetMode;targetMode=s.mode;modeBlend=0.f;modeRemaining=juce::jmax(1,(int)(rate*.01));modeStep=1.f/(float)modeRemaining;}auto targetWet=s.bypass?0.f:1.f;if(targetWet!=(eqRemaining>0?eqWet+eqStep*eqRemaining:eqWet)){eqRemaining=juce::jmax(1,(int)(rate*.01));eqStep=(targetWet-eqWet)/(float)eqRemaining;}settings=s;if(coefficientsChanged)configureFilters();}
void ComparisonProcessor::configureFilters()noexcept{auto set=[](Biquad&filter,const Coefficients&c){filter.set(c.b0,c.b1,c.b2,1,c.a1,c.a2);};auto hp=design(FilterType::highPass,settings.highPassHz,.707f,0,rate);auto bp=design(FilterType::bandPass,settings.bandPassHz,settings.bandPassQ,settings.bandPassGainDb,rate);auto lp=design(FilterType::lowPass,settings.lowPassHz,.707f,0,rate);for(auto*chain:{&mixChain,&referenceChain})for(auto&ch:chain->channel){set(ch.hp1,hp);set(ch.hp2,hp);set(ch.bandPass,bp);set(ch.lp1,lp);set(ch.lp2,lp);}}
float ComparisonProcessor::responseDecibelsAt(const ComparisonSettings&s,float frequency,double sampleRate)noexcept{if(s.bypass)return 0;double response=1;if(s.highPassEnabled){auto value=magnitude(design(FilterType::highPass,s.highPassHz,.707f,0,sampleRate),frequency,sampleRate);response*=value;if(s.highPassSlope>=24)response*=value;}if(s.bandPassEnabled)response*=magnitude(design(FilterType::bandPass,s.bandPassHz,s.bandPassQ,s.bandPassGainDb,sampleRate),frequency,sampleRate);if(s.lowPassEnabled){auto value=magnitude(design(FilterType::lowPass,s.lowPassHz,.707f,0,sampleRate),frequency,sampleRate);response*=value;if(s.lowPassSlope>=24)response*=value;}return juce::Decibels::gainToDecibels((float)response,-100.f);}
std::pair<float,float> ComparisonProcessor::transformed(float l,float r,ListeningMode m)noexcept{const float mid=.5f*(l+r);const float side=.5f*(l-r);switch(m){case ListeningMode::mono:case ListeningMode::mid:return{mid,mid};case ListeningMode::side:return{side,-side};case ListeningMode::stereo:return{l,r};}return{l,r};}
void ComparisonProcessor::applyListeningMode(juce::AudioBuffer<float>&b,ListeningMode m)noexcept{if(b.getNumChannels()<2)return;for(int i=0;i<b.getNumSamples();++i){auto v=transformed(b.getSample(0,i),b.getSample(1,i),m);b.setSample(0,i,v.first);b.setSample(1,i,v.second);}}
void ComparisonProcessor::processModes(juce::AudioBuffer<float>&a,juce::AudioBuffer<float>&b)noexcept{for(int i=0;i<a.getNumSamples();++i){if(modeRemaining>0){modeBlend+=modeStep;if(--modeRemaining==0)modeBlend=1.f;}for(auto*buffer:{&a,&b}){if(buffer->getNumChannels()<2)continue;const float l=buffer->getSample(0,i);const float r=buffer->getSample(1,i);const auto old=transformed(l,r,previousMode);const auto next=transformed(l,r,targetMode);buffer->setSample(0,i,juce::jmap(modeBlend,old.first,next.first));buffer->setSample(1,i,juce::jmap(modeBlend,old.second,next.second));}}}
void ComparisonProcessor::processEq(juce::AudioBuffer<float>&b,Chain&chain,float wet)noexcept{for(int c=0;c<juce::jmin(2,b.getNumChannels());++c){auto&f=chain.channel[c];for(int i=0;i<b.getNumSamples();++i){const float dry=b.getSample(c,i);float x=dry;if(settings.highPassEnabled){x=f.hp1.process(x);if(settings.highPassSlope>=24)x=f.hp2.process(x);}if(settings.bandPassEnabled)x=f.bandPass.process(x);if(settings.lowPassEnabled){x=f.lp1.process(x);if(settings.lowPassSlope>=24)x=f.lp2.process(x);}b.setSample(c,i,juce::jmap(wet,dry,x));}}}
void ComparisonProcessor::process(juce::AudioBuffer<float>&a,juce::AudioBuffer<float>&b)noexcept{processModes(a,b);auto wet=eqWet;if(eqRemaining>0){auto steps=juce::jmin(eqRemaining,a.getNumSamples());eqWet+=eqStep*steps;eqRemaining-=steps;if(eqRemaining==0)eqWet=settings.bypass?0.f:1.f;wet=.5f*(wet+eqWet);}processEq(a,mixChain,wet);processEq(b,referenceChain,wet);}
}
