#include "ComparisonProcessor.h"
#include <cmath>
namespace referencelab {
void ComparisonProcessor::prepare(double sr,int)noexcept{rate=sr>0?sr:44100.0;for(auto*c:{&mixChain,&referenceChain})for(auto&ch:c->channel){ch.hp1.reset();ch.hp2.reset();ch.bell.reset();ch.lp1.reset();ch.lp2.reset();}previousMode=targetMode=settings.mode;modeBlend=1.f;eqWet=settings.bypass?0.f:1.f;configureFilters();}
void ComparisonProcessor::update(const ComparisonSettings&s)noexcept{auto coefficientsChanged=s.highPassHz!=settings.highPassHz||s.bellHz!=settings.bellHz||s.bellGainDb!=settings.bellGainDb||s.bellQ!=settings.bellQ||s.lowPassHz!=settings.lowPassHz;if(s.mode!=targetMode){previousMode=targetMode;targetMode=s.mode;modeBlend=0.f;modeRemaining=juce::jmax(1,(int)(rate*.01));modeStep=1.f/(float)modeRemaining;}auto targetWet=s.bypass?0.f:1.f;if(targetWet!=(eqRemaining>0?eqWet+eqStep*eqRemaining:eqWet)){eqRemaining=juce::jmax(1,(int)(rate*.01));eqStep=(targetWet-eqWet)/(float)eqRemaining;}settings=s;if(coefficientsChanged)configureFilters();}
void ComparisonProcessor::configureFilters()noexcept{auto design=[&](int type,float hz,float q,float gain,Biquad&b){const double w=2.0*juce::MathConstants<double>::pi*juce::jlimit(10.0,rate*.49,(double)hz)/rate;const double c=std::cos(w);const double sine=std::sin(w);const double alpha=sine/(2.0*juce::jmax(.1,(double)q));if(type==0)b.set((1+c)/2,-(1+c),(1+c)/2,1+alpha,-2*c,1-alpha);else if(type==1)b.set((1-c)/2,1-c,(1-c)/2,1+alpha,-2*c,1-alpha);else{const double A=std::pow(10.0,gain/40.0);b.set(1+alpha*A,-2*c,1-alpha*A,1+alpha/A,-2*c,1-alpha/A);}};for(auto*chain:{&mixChain,&referenceChain})for(auto&ch:chain->channel){design(0,settings.highPassHz,.707f,0,ch.hp1);design(0,settings.highPassHz,.707f,0,ch.hp2);design(2,settings.bellHz,settings.bellQ,settings.bellGainDb,ch.bell);design(1,settings.lowPassHz,.707f,0,ch.lp1);design(1,settings.lowPassHz,.707f,0,ch.lp2);}}
std::pair<float,float> ComparisonProcessor::transformed(float l,float r,ListeningMode m)noexcept{const float mid=.5f*(l+r);const float side=.5f*(l-r);switch(m){case ListeningMode::mono:case ListeningMode::mid:return{mid,mid};case ListeningMode::side:return{side,-side};case ListeningMode::stereo:return{l,r};}return{l,r};}
void ComparisonProcessor::applyListeningMode(juce::AudioBuffer<float>&b,ListeningMode m)noexcept{if(b.getNumChannels()<2)return;for(int i=0;i<b.getNumSamples();++i){auto v=transformed(b.getSample(0,i),b.getSample(1,i),m);b.setSample(0,i,v.first);b.setSample(1,i,v.second);}}
void ComparisonProcessor::processModes(juce::AudioBuffer<float>&a,juce::AudioBuffer<float>&b)noexcept{for(int i=0;i<a.getNumSamples();++i){if(modeRemaining>0){modeBlend+=modeStep;if(--modeRemaining==0)modeBlend=1.f;}for(auto*buffer:{&a,&b}){if(buffer->getNumChannels()<2)continue;const float l=buffer->getSample(0,i);const float r=buffer->getSample(1,i);const auto old=transformed(l,r,previousMode);const auto next=transformed(l,r,targetMode);buffer->setSample(0,i,juce::jmap(modeBlend,old.first,next.first));buffer->setSample(1,i,juce::jmap(modeBlend,old.second,next.second));}}}
void ComparisonProcessor::processEq(juce::AudioBuffer<float>&b,Chain&chain,float wet)noexcept{for(int c=0;c<juce::jmin(2,b.getNumChannels());++c){auto&f=chain.channel[c];for(int i=0;i<b.getNumSamples();++i){const float dry=b.getSample(c,i);float x=dry;if(settings.highPassEnabled){x=f.hp1.process(x);if(settings.highPassSlope>=24)x=f.hp2.process(x);}if(settings.bellEnabled)x=f.bell.process(x);if(settings.lowPassEnabled){x=f.lp1.process(x);if(settings.lowPassSlope>=24)x=f.lp2.process(x);}b.setSample(c,i,juce::jmap(wet,dry,x));}}}
void ComparisonProcessor::process(juce::AudioBuffer<float>&a,juce::AudioBuffer<float>&b)noexcept{processModes(a,b);auto wet=eqWet;if(eqRemaining>0){auto steps=juce::jmin(eqRemaining,a.getNumSamples());eqWet+=eqStep*steps;eqRemaining-=steps;if(eqRemaining==0)eqWet=settings.bypass?0.f:1.f;wet=.5f*(wet+eqWet);}processEq(a,mixChain,wet);processEq(b,referenceChain,wet);}
}
