#include "HeadphoneProfile.h"

namespace referencelab {
namespace {
juce::String typeName(HeadphoneFilterType type){switch(type){case HeadphoneFilterType::lowShelf:return"LOW_SHELF";case HeadphoneFilterType::highShelf:return"HIGH_SHELF";default:return"PEAKING";}}
}
juce::var HeadphoneFilter::toVar()const{auto*o=new juce::DynamicObject;o->setProperty("type",typeName(type));o->setProperty("frequency",frequency);o->setProperty("gainDb",gainDb);o->setProperty("q",q);return o;}
std::optional<HeadphoneFilter>HeadphoneFilter::fromVar(const juce::var&v,juce::String&error){auto*o=v.getDynamicObject();if(!o){error="Invalid headphone filter";return{};}HeadphoneFilter f;auto type=o->getProperty("type").toString();f.type=type=="LOW_SHELF"?HeadphoneFilterType::lowShelf:type=="HIGH_SHELF"?HeadphoneFilterType::highShelf:HeadphoneFilterType::peaking;f.frequency=(float)o->getProperty("frequency");f.gainDb=(float)o->getProperty("gainDb");f.q=(float)o->getProperty("q");if(f.frequency<10.f||f.frequency>40000.f||f.q<=0.f||f.q>30.f||f.gainDb<-30.f||f.gainDb>30.f){error="Headphone filter values are out of range";return{};}return f;}
juce::var HeadphoneProfile::toVar()const{auto*o=new juce::DynamicObject;o->setProperty("id",id);o->setProperty("name",name);o->setProperty("headphone",headphone);o->setProperty("source",source);o->setProperty("form",form);o->setProperty("rig",rig);o->setProperty("target",target);o->setProperty("preampDb",preampDb);juce::Array<juce::var>a;for(auto&f:filters)a.add(f.toVar());o->setProperty("filters",a);return o;}
std::optional<HeadphoneProfile>HeadphoneProfile::fromVar(const juce::var&v,juce::String&error){auto*o=v.getDynamicObject();if(!o){error="Invalid headphone profile";return{};}HeadphoneProfile p;p.id=o->getProperty("id").toString();p.name=o->getProperty("name").toString();p.headphone=o->getProperty("headphone").toString();p.source=o->getProperty("source").toString();p.form=o->getProperty("form").toString();p.rig=o->getProperty("rig").toString();p.target=o->getProperty("target").toString();p.preampDb=(float)o->getProperty("preampDb");if(p.id.isEmpty()||p.name.isEmpty()||p.preampDb>0.f||p.preampDb<-40.f){error="Invalid headphone profile metadata";return{};}if(auto*a=o->getProperty("filters").getArray())for(auto&item:*a){auto f=HeadphoneFilter::fromVar(item,error);if(!f)return{};p.filters.push_back(*f);}if(p.filters.empty()||p.filters.size()>16){error="A headphone profile must contain 1 to 16 filters";return{};}return p;}
}
