#include "AirwindowsMeter.h"
#include <cmath>

namespace referencelab {
AirwindowsMeter::AirwindowsMeter(AirwindowsMeterModel&m):model(m){setMouseCursor(juce::MouseCursor::PointingHandCursor);setTooltip("Airwindows Meter - doppio clic per azzerare");startTimerHz(30);}
void AirwindowsMeter::reset(){history={};writePosition=valid=0;repaint();}
void AirwindowsMeter::mouseDoubleClick(const juce::MouseEvent&){reset();}
void AirwindowsMeter::timerCallback(){AirwindowsMeterFrame incoming[32];const auto count=model.pull(incoming,32);for(int i=0;i<count;++i){history[(size_t)writePosition]=incoming[i];writePosition=(writePosition+1)%historySize;valid=juce::jmin(historySize,valid+1);}if(count>0)repaint();}
void AirwindowsMeter::drawLane(juce::Graphics&g,juce::Rectangle<float>area,const juce::String&name,int lane)const{g.setColour(juce::Colour(0xff101820));g.fillRoundedRectangle(area,6.f);g.setColour(juce::Colours::white.withAlpha(.12f));for(int i=1;i<4;++i)g.drawHorizontalLine((int)(area.getY()+area.getHeight()*i/4.f),area.getX(),area.getRight());g.setColour(juce::Colours::white.withAlpha(.72f));g.setFont(11.f);g.drawText(name,area.toNearestInt().removeFromTop(20).reduced(8,0),juce::Justification::left);if(valid==0)return;const auto step=area.getWidth()/juce::jmax(1,valid-1);for(int i=0;i<valid;++i){const auto index=(writePosition-valid+i+historySize)%historySize;const auto&f=history[(size_t)index];float l=0,r=0;juce::Colour colour;if(lane==0){l=f.peakL;r=f.peakR;colour=juce::Colours::white;}else if(lane==1){l=std::sqrt(juce::jmax(0.f,f.slewL));r=std::sqrt(juce::jmax(0.f,f.slewR));colour=juce::Colour(0xff36b8e8);}else{l=f.bassL;r=f.bassR;colour=juce::Colour(0xffff9c45);}const auto x=area.getX()+i*step,y1=area.getBottom()-juce::jlimit(0.f,1.f,l)*area.getHeight()*.88f,y2=area.getBottom()-juce::jlimit(0.f,1.f,r)*area.getHeight()*.88f;g.setColour(colour.withAlpha(.8f));g.fillEllipse(x-1.5f,y1-1.5f,3.f,3.f);g.setColour(colour.withAlpha(.38f));g.fillEllipse(x-1.2f,y2-1.2f,2.4f,2.4f);}}
void AirwindowsMeter::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff111820));auto area=getLocalBounds().toFloat().reduced(14);auto title=area.removeFromTop(38);g.setColour(juce::Colours::white);g.setFont(juce::FontOptions(16.f,juce::Font::bold));g.drawText("AIRWINDOWS METER",title.toNearestInt(),juce::Justification::centredLeft);g.setColour(juce::Colours::white.withAlpha(.55f));g.setFont(11.f);g.drawText("PEAK / SLEW / BASS  |  doppio clic: reset",title.toNearestInt(),juce::Justification::centredRight);const auto gap=8.f,height=(area.getHeight()-gap*2)/3.f;drawLane(g,area.removeFromTop(height),"PEAK STRUCTURE",0);area.removeFromTop(gap);drawLane(g,area.removeFromTop(height),"SLEW / TRANSIENTS",1);area.removeFromTop(gap);drawLane(g,area,"BASS / ZERO ENERGY",2);}
}
