#include "AnalysisDisplay.h"
#include <algorithm>
#include <cmath>
namespace referencelab {
AnalysisDisplay::AnalysisDisplay(SampleFifo&m,SampleFifo&r,SampleFifo&o):mixFifo(m),referenceFifo(r),outputFifo(o){mixSpectrum.fill(-100.f);referenceSpectrum.fill(-100.f);startTimerHz(30);}
void AnalysisDisplay::consume(SampleFifo&fifo,std::array<float,size>&target){auto count=fifo.pull(scratch.data(),size);if(count<=0)return;if(count>=size)std::copy_n(scratch.end()-size,size,target.begin());else{std::move(target.begin()+count,target.end(),target.begin());std::copy_n(scratch.begin(),count,target.end()-count);}}
void AnalysisDisplay::calculate(const std::array<float,size>&time,std::array<float,size*2>&data,std::array<float,size/2>&spectrum){std::fill(data.begin(),data.end(),0.f);std::copy(time.begin(),time.end(),data.begin());window.multiplyWithWindowingTable(data.data(),size);fft.performFrequencyOnlyForwardTransform(data.data());for(int i=0;i<size/2;++i){auto db=juce::Decibels::gainToDecibels(data[(size_t)i]/(float)size,-100.f);spectrum[(size_t)i]+=.22f*(db-spectrum[(size_t)i]);}}
void AnalysisDisplay::timerCallback(){if(frozen)return;consume(mixFifo,mixTime);consume(referenceFifo,referenceTime);consume(outputFifo,outputTime);calculate(mixTime,mixFft,mixSpectrum);calculate(referenceTime,referenceFft,referenceSpectrum);repaint();}
juce::Path AnalysisDisplay::spectrumPath(const std::array<float,size/2>&values,juce::Rectangle<float>area)const{juce::Path p;for(int x=0;x<(int)area.getWidth();++x){auto proportion=(float)x/juce::jmax(1.f,area.getWidth()-1.f);auto bin=juce::jlimit(1,size/2-1,(int)std::pow((float)(size/2-1),proportion));auto y=juce::jmap(juce::jlimit(-90.f,0.f,values[(size_t)bin]),-90.f,0.f,area.getBottom(),area.getY());if(x==0)p.startNewSubPath(area.getX(),y);else p.lineTo(area.getX()+(float)x,y);}return p;}
void AnalysisDisplay::paint(juce::Graphics&g){auto all=getLocalBounds().toFloat();g.fillAll(juce::Colour(0xff151d27));auto spectrum=all.removeFromTop(all.getHeight()*.68f).reduced(8);g.setColour(juce::Colours::white.withAlpha(.08f));for(int i=1;i<6;++i){auto y=juce::jmap((float)i,0.f,6.f,spectrum.getY(),spectrum.getBottom());g.drawHorizontalLine((int)y,spectrum.getX(),spectrum.getRight());}g.setColour(juce::Colour(0xff54c6eb));g.strokePath(spectrumPath(mixSpectrum,spectrum),juce::PathStrokeType(1.5f));g.setColour(juce::Colour(0xffff9f43));g.strokePath(spectrumPath(referenceSpectrum,spectrum),juce::PathStrokeType(1.5f));auto scope=all.reduced(8);juce::Path wave;for(int x=0;x<(int)scope.getWidth();++x){auto index=(size_t)juce::jlimit(0,size-1,(int)((float)x/scope.getWidth()*size));auto y=scope.getCentreY()-outputTime[index]*scope.getHeight()*.45f;if(x==0)wave.startNewSubPath(scope.getX(),y);else wave.lineTo(scope.getX()+x,y);}g.setColour(juce::Colour(0xff9be564));g.strokePath(wave,juce::PathStrokeType(1.f));g.setColour(juce::Colours::white.withAlpha(.65f));g.drawText("FFT  MIX / REFERENCE",spectrum.toNearestInt().removeFromTop(20),juce::Justification::left);g.drawText("OUTPUT SCOPE",scope.toNearestInt().removeFromTop(20),juce::Justification::left);}
}
