#include "AnalysisDisplay.h"
#include <algorithm>
#include <cmath>
#include <complex>
namespace referencelab {
AnalysisDisplay::AnalysisDisplay(SampleFifo&m,SampleFifo&r,SampleFifo&o,juce::AudioProcessorValueTreeState&s):mixFifo(m),referenceFifo(r),outputFifo(o),state(s){mixSpectrum.fill(-100);referenceSpectrum.fill(-100);setFftOrder(11);startTimerHz(30);}
void AnalysisDisplay::setFftOrder(int order){currentOrder=juce::jlimit(10,maxOrder,order);currentSize=1<<currentOrder;fft=std::make_unique<juce::dsp::FFT>(currentOrder);window=std::make_unique<juce::dsp::WindowingFunction<float>>(currentSize,juce::dsp::WindowingFunction<float>::hann);mixSpectrum.fill(-100);referenceSpectrum.fill(-100);}
void AnalysisDisplay::consume(SampleFifo&fifo,std::array<float,maxSize>&target){const int count=fifo.pull(scratch.data(),maxSize);if(count<=0)return;if(count>=maxSize)std::copy_n(scratch.end()-maxSize,maxSize,target.begin());else{std::move(target.begin()+count,target.end(),target.begin());std::copy_n(scratch.begin(),count,target.end()-count);}}
void AnalysisDisplay::calculate(const std::array<float,maxSize>&time,std::array<float,maxSize*2>&data,std::array<float,maxSize/2>&spectrum){std::fill(data.begin(),data.end(),0.f);std::copy_n(time.end()-currentSize,currentSize,data.begin());window->multiplyWithWindowingTable(data.data(),currentSize);fft->performFrequencyOnlyForwardTransform(data.data());for(int i=0;i<currentSize/2;++i){const float db=juce::Decibels::gainToDecibels(data[(size_t)i]/(float)currentSize,-100.f);spectrum[(size_t)i]+=smoothing*(db-spectrum[(size_t)i]);}}
void AnalysisDisplay::timerCallback(){if(frozen)return;consume(mixFifo,mixTime);consume(referenceFifo,referenceTime);consume(outputFifo,outputTime);calculate(mixTime,mixFft,mixSpectrum);calculate(referenceTime,referenceFft,referenceSpectrum);repaint();}
juce::Path AnalysisDisplay::spectrumPath(const std::array<float,maxSize/2>&values,juce::Rectangle<float>area)const{juce::Path p;for(int x=0;x<(int)area.getWidth();++x){auto proportion=(float)x/juce::jmax(1.f,area.getWidth()-1);auto frequency=20.f*std::pow(1000.f,proportion);auto bin=juce::jlimit(1,currentSize/2-1,(int)(frequency/sampleRate*currentSize));auto y=juce::jmap(juce::jlimit(-90.f,0.f,values[(size_t)bin]),-90.f,0.f,area.getBottom(),area.getY());if(x==0)p.startNewSubPath(area.getX(),y);else p.lineTo(area.getX()+x,y);}return p;}
float AnalysisDisplay::eqDbAt(float f)const{if(state.getRawParameterValue("eqBypass")->load()>.5f)return 0;auto hp=state.getRawParameterValue("hpf")->load(),lp=state.getRawParameterValue("lpf")->load(),bf=state.getRawParameterValue("bellFreq")->load(),gain=state.getRawParameterValue("bellGain")->load(),q=state.getRawParameterValue("bellQ")->load();float db=0;if(state.getRawParameterValue("hpfEnabled")->load()>.5f){auto order=state.getRawParameterValue("hpfSlope")->load()>.5f?4.f:2.f;db+=(float)(-10*std::log10(1+std::pow(hp/f,2*order)));}if(state.getRawParameterValue("lpfEnabled")->load()>.5f){auto order=state.getRawParameterValue("lpfSlope")->load()>.5f?4.f:2.f;db+=(float)(-10*std::log10(1+std::pow(f/lp,2*order)));}if(state.getRawParameterValue("bellEnabled")->load()>.5f){auto oct=(float)std::log2(f/bf);auto width=juce::jmax(.08f,1.f/q);db+=gain*std::exp(-.5f*oct*oct/(width*width));}return juce::jlimit(-36.f,18.f,db);}
juce::Path AnalysisDisplay::eqPath(juce::Rectangle<float>area)const{juce::Path p;for(int x=0;x<(int)area.getWidth();++x){auto proportion=x/juce::jmax(1.f,area.getWidth()-1);auto frequency=20.f*std::pow(1000.f,proportion);auto y=juce::jmap(eqDbAt(frequency),-36.f,18.f,area.getBottom(),area.getY());if(x==0)p.startNewSubPath(area.getX(),y);else p.lineTo(area.getX()+x,y);}return p;}
void AnalysisDisplay::paint(juce::Graphics&g){auto all=getLocalBounds().toFloat();g.fillAll(juce::Colour(0xff151d27));auto spectrum=all.removeFromTop(all.getHeight()*.68f).reduced(8);g.setFont(10);for(auto db:{0,-18,-36,-54,-72,-90}){auto y=juce::jmap((float)db,-90.f,0.f,spectrum.getBottom(),spectrum.getY());g.setColour(juce::Colours::white.withAlpha(.08f));g.drawHorizontalLine((int)y,spectrum.getX(),spectrum.getRight());g.setColour(juce::Colours::white.withAlpha(.45f));g.drawText(juce::String(db)+" dB",(int)spectrum.getX()+2,(int)y-12,42,12,juce::Justification::left);}for(auto f:{20,50,100,200,500,1000,2000,5000,10000,20000}){auto x=spectrum.getX()+std::log10(f/20.f)/3.f*spectrum.getWidth();g.setColour(juce::Colours::white.withAlpha(.07f));g.drawVerticalLine((int)x,spectrum.getY(),spectrum.getBottom());g.setColour(juce::Colours::white.withAlpha(.45f));g.drawText(f>=1000?juce::String(f/1000)+"k":juce::String(f),(int)x-14,(int)spectrum.getBottom()-14,28,12,juce::Justification::centred);}g.setColour(juce::Colour(0xff54c6eb));g.strokePath(spectrumPath(mixSpectrum,spectrum),juce::PathStrokeType(1.5f));g.setColour(juce::Colour(0xffff9f43));g.strokePath(spectrumPath(referenceSpectrum,spectrum),juce::PathStrokeType(1.5f));g.setColour(juce::Colour(0xff9be564));g.strokePath(eqPath(spectrum),juce::PathStrokeType(1.8f));auto legend=spectrum.toNearestInt().removeFromTop(20);g.setColour(juce::Colour(0xff54c6eb));g.drawText("MIX",legend.removeFromLeft(35),juce::Justification::left);g.setColour(juce::Colour(0xffff9f43));g.drawText("REFERENCE",legend.removeFromLeft(72),juce::Justification::left);g.setColour(juce::Colour(0xff9be564));g.drawText("EQ",legend.removeFromLeft(30),juce::Justification::left);auto scope=all.reduced(8);juce::Path wave;for(int x=0;x<(int)scope.getWidth();++x){auto index=juce::jlimit(0,maxSize-1,(int)(x/juce::jmax(1.f,scope.getWidth())*maxSize));auto y=scope.getCentreY()-outputTime[(size_t)index]*scope.getHeight()*.45f;if(x==0)wave.startNewSubPath(scope.getX(),y);else wave.lineTo(scope.getX()+x,y);}g.setColour(juce::Colour(0xff9be564));g.strokePath(wave,juce::PathStrokeType(1));g.setColour(juce::Colours::white.withAlpha(.65f));g.drawText("OUTPUT SCOPE",scope.toNearestInt().removeFromTop(20),juce::Justification::left);}
}
