#include "ReferenceWaveform.h"
#include <cmath>
#include <vector>
namespace referencelab {
ReferenceWaveform::ReferenceWaveform(ReferencePlayer&p):player(p){startTimerHz(30);}
double ReferenceWaveform::duration()const noexcept{return player.getDurationSeconds();}double ReferenceWaveform::xToSeconds(float x)const noexcept{auto d=duration();return d<=0?0:juce::jlimit(0.0,d,viewStart+juce::jlimit(0.f,1.f,x/(float)juce::jmax(1,getWidth()))*viewLength*d);}float ReferenceWaveform::secondsToX(double s)const noexcept{auto d=duration();return d<=0?0:(float)((s/d-viewStart)/viewLength*getWidth());}void ReferenceWaveform::setLoop(bool e,double a,double b)noexcept{loopEnabled=e;loopStart=a;loopEnd=b;repaint();}
void ReferenceWaveform::paint(juce::Graphics&g){auto area=getLocalBounds().toFloat();g.setColour(juce::Colour(0xff111923));g.fillRoundedRectangle(area,5);auto audio=player.getAudioSnapshot();if(!audio||audio->samples.getNumSamples()==0){g.setColour(juce::Colours::grey);g.drawText("Nessuna waveform",getLocalBounds(),juce::Justification::centred);return;}auto d=duration();auto first=(int)(viewStart*audio->samples.getNumSamples()),count=juce::jmax(1,(int)(viewLength*audio->samples.getNumSamples()));juce::Path path;auto centre=area.getCentreY();std::vector<float>peaks((size_t)getWidth());for(int x=0;x<getWidth();++x){auto a=juce::jlimit(0,audio->samples.getNumSamples()-1,first+(int)((double)x/getWidth()*count)),b=juce::jlimit(a+1,audio->samples.getNumSamples(),first+(int)((double)(x+1)/getWidth()*count));auto step=juce::jmax(1,(b-a)/8);for(int i=a;i<b;i+=step)peaks[(size_t)x]=juce::jmax(peaks[(size_t)x],std::abs(audio->samples.getSample(0,i)),std::abs(audio->samples.getSample(1,i)));auto h=peaks[(size_t)x]*area.getHeight()*.42f;if(x==0)path.startNewSubPath(0,centre-h);else path.lineTo((float)x,centre-h);}for(int x=getWidth()-1;x>=0;--x)path.lineTo((float)x,centre+peaks[(size_t)x]*area.getHeight()*.42f);path.closeSubPath();g.setColour(juce::Colour(0xffe99845).withAlpha(.75f));g.fillPath(path);if(loopEnabled&&loopEnd>loopStart){auto x1=secondsToX(loopStart),x2=secondsToX(loopEnd);g.setColour(juce::Colour(0x334bc0ff));g.fillRect(juce::Rectangle<float>(x1,0,x2-x1,area.getHeight()));g.setColour(juce::Colour(0xff4bc0ff));g.drawVerticalLine((int)x1,0,area.getHeight());g.drawVerticalLine((int)x2,0,area.getHeight());g.drawText("A",(int)x1+3,2,20,18,juce::Justification::left);g.drawText("B",(int)x2-23,2,20,18,juce::Justification::right);}auto current=secondsToX(player.getPositionSeconds());g.setColour(juce::Colours::white);g.drawVerticalLine((int)current,0,area.getHeight());g.drawText(juce::String(player.getPositionSeconds(),1)+" / "+juce::String(d,1)+" s",6,getHeight()-22,160,18,juce::Justification::left);}
void ReferenceWaveform::mouseDown(const juce::MouseEvent&e){dragStartX=e.x;dragViewStart=viewStart;if(e.mods.isRightButtonDown()||e.mods.isMiddleButtonDown())drag=Drag::pan;else if(loopEnabled&&std::abs(e.x-secondsToX(loopStart))<8)drag=Drag::start;else if(loopEnabled&&std::abs(e.x-secondsToX(loopEnd))<8)drag=Drag::end;else{drag=Drag::seek;auto s=xToSeconds((float)e.x);player.seek(s);if(onSeek)onSeek(s);}}void ReferenceWaveform::mouseDrag(const juce::MouseEvent&e){if(drag==Drag::pan)viewStart=juce::jlimit(0.0,1.0-viewLength,dragViewStart-(e.x-dragStartX)/(double)getWidth()*viewLength);else if(drag==Drag::start)loopStart=juce::jlimit(0.0,loopEnd-.01,xToSeconds((float)e.x));else if(drag==Drag::end)loopEnd=juce::jlimit(loopStart+.01,duration(),xToSeconds((float)e.x));else{auto s=xToSeconds((float)e.x);player.seek(s);if(onSeek)onSeek(s);}repaint();}void ReferenceWaveform::mouseUp(const juce::MouseEvent&){if((drag==Drag::start||drag==Drag::end)&&onLoopChanged)onLoopChanged(loopStart,loopEnd);}void ReferenceWaveform::mouseWheelMove(const juce::MouseEvent&e,const juce::MouseWheelDetails&w){auto old=viewLength;viewLength=juce::jlimit(.05,1.0,viewLength*(w.deltaY>0?.75:1.333));auto anchor=viewStart+old*e.position.x/getWidth();viewStart=juce::jlimit(0.0,1.0-viewLength,anchor-viewLength*e.position.x/getWidth());repaint();}void ReferenceWaveform::timerCallback(){repaint();}
}
