#include "PluginEditor.h"
ReferenceLabEditor::ReferenceLabEditor(ReferenceLabAudioProcessor&x):AudioProcessorEditor(x),p(x),analysisDisplay(x.getMixFifo(),x.getReferenceFifo(),x.getOutputFifo(),x.state),waveform(x.getPlayer()){
    setResizable(true,true);setWantsKeyboardFocus(true);setResizeLimits(900,650,1800,1200);setSize(juce::jlimit(900,1800,(int)p.state.state.getProperty("uiWidth",1100)),juce::jlimit(650,1200,(int)p.state.state.getProperty("uiHeight",780)));
    addAndMakeVisible(add);
    addAndMakeVisible(scan);
    addAndMakeVisible(importCatalog);addAndMakeVisible(addUrl);
    addAndMakeVisible(playlist);addAndMakeVisible(newPlaylist);addAndMakeVisible(addToPlaylist);addAndMakeVisible(previousReference);addAndMakeVisible(nextReference);
    addAndMakeVisible(remove);
    addAndMakeVisible(relink);addAndMakeVisible(recursiveScan);
    addAndMakeVisible(save);
    addAndMakeVisible(savePreset);addAndMakeVisible(loadPreset);
    addAndMakeVisible(resetMeters);addAndMakeVisible(freezeDisplay);addAndMakeVisible(safeExport);addAndMakeVisible(matchBypass);
    addAndMakeVisible(mix);
    addAndMakeVisible(ref);
    addAndMakeVisible(play);
    addAndMakeVisible(pause);
    addAndMakeVisible(stop);
    addAndMakeVisible(title);
    addAndMakeVisible(search);
    for(auto*e:{&filterArtist,&filterGenre,&filterKey,&minBpm,&maxBpm,&editAlbum,&editYear,&editKey,&editRating,&editNotes})addAndMakeVisible(e);
    addAndMakeVisible(favouritesOnly);
    addAndMakeVisible(editFavourite);
    addAndMakeVisible(sort);
    addAndMakeVisible(cacheSize);
    addAndMakeVisible(autoMatch);
    addAndMakeVisible(matchMode);
    addAndMakeVisible(syncMode);
    addAndMakeVisible(manualGain);
    addAndMakeVisible(loopEnabled);addAndMakeVisible(eqBypass);addAndMakeVisible(listeningMode);
    addAndMakeVisible(hpfEnabled);addAndMakeVisible(bellEnabled);addAndMakeVisible(lpfEnabled);addAndMakeVisible(hpfSlope);addAndMakeVisible(lpfSlope);
    addAndMakeVisible(fftSize);addAndMakeVisible(displayRate);addAndMakeVisible(fftSmoothing);
    addAndMakeVisible(transportSync);addAndMakeVisible(transportStatus);
    for(auto*s:{&seek,&startOffset,&loopStart,&loopEnd,&fade,&hpf,&bellFreq,&bellGain,&bellQ,&lpf,&syncOffset})addAndMakeVisible(s);
    addAndMakeVisible(mixMeters);addAndMakeVisible(referenceMeters);addAndMakeVisible(outputMeters);addAndMakeVisible(matchedGain);
    addAndMakeVisible(editTitle);
    addAndMakeVisible(editArtist);
    addAndMakeVisible(editGenre);
    addAndMakeVisible(editBpm);
    addAndMakeVisible(editTags);
    addAndMakeVisible(list);
    addAndMakeVisible(analysisDisplay);
    analysisDisplay.setSampleRate(p.getSampleRate());
    addAndMakeVisible(waveform);waveform.onSeek=[this](double value){seek.setValue(value,juce::dontSendNotification);};waveform.onLoopChanged=[this](double a,double b){loopStart.setValue(a,juce::dontSendNotification);loopEnd.setValue(b,juce::dontSendNotification);applyLoop();persistPlayback();};
    title.setText("ReferenceLab 2.0",juce::dontSendNotification);search.setTextToShowWhenEmpty("Cerca titolo, artista, album, genere, tag...",juce::Colours::grey);
    editTitle.setTextToShowWhenEmpty("Titolo",juce::Colours::grey);editArtist.setTextToShowWhenEmpty("Artista",juce::Colours::grey);editAlbum.setTextToShowWhenEmpty("Album",juce::Colours::grey);editGenre.setTextToShowWhenEmpty("Genere",juce::Colours::grey);editYear.setTextToShowWhenEmpty("Anno",juce::Colours::grey);editBpm.setTextToShowWhenEmpty("BPM",juce::Colours::grey);editKey.setTextToShowWhenEmpty("Tonalità",juce::Colours::grey);editRating.setTextToShowWhenEmpty("Rating 0-5",juce::Colours::grey);editTags.setTextToShowWhenEmpty("Tag separati da virgola",juce::Colours::grey);editNotes.setTextToShowWhenEmpty("Note",juce::Colours::grey);filterArtist.setTextToShowWhenEmpty("Filtro artista",juce::Colours::grey);filterGenre.setTextToShowWhenEmpty("Filtro genere",juce::Colours::grey);filterKey.setTextToShowWhenEmpty("Tonalità",juce::Colours::grey);minBpm.setTextToShowWhenEmpty("BPM min",juce::Colours::grey);maxBpm.setTextToShowWhenEmpty("BPM max",juce::Colours::grey);recursiveScan.setToggleState(true,juce::dontSendNotification);
    sort.addItemList({"Titolo","Artista","Genere","BPM","Rating","Data aggiunta","Ultimo uso"},1);sort.setSelectedId(1,juce::dontSendNotification);
    cacheSize.addItemList({"Cache 128 MB","Cache 256 MB","Cache 512 MB","Cache 1024 MB"},1);cacheSize.setSelectedId(3,juce::dontSendNotification);
    matchMode.addItemList({"Integrated","Short-Term","Momentary"},1);manualGain.setSliderStyle(juce::Slider::LinearHorizontal);manualGain.setTextBoxStyle(juce::Slider::TextBoxRight,false,64,24);manualGain.setTextValueSuffix(" dB");
    syncMode.addItemList({"Timeline","Restart on Play"},1);listeningMode.addItemList({"Stereo","Mono","Mid","Side"},1);
    hpfSlope.addItemList({"12 dB/oct","24 dB/oct"},1);lpfSlope.addItemList({"12 dB/oct","24 dB/oct"},1);
    fftSize.addItemList({"FFT 1024","FFT 2048","FFT 4096"},1);displayRate.addItemList({"15 Hz","30 Hz","60 Hz"},1);fftSmoothing.setSliderStyle(juce::Slider::LinearHorizontal);fftSmoothing.setTextBoxStyle(juce::Slider::TextBoxRight,false,55,22);
    for(auto*s:{&seek,&startOffset,&loopStart,&loopEnd,&fade,&hpf,&bellFreq,&bellGain,&bellQ,&lpf,&syncOffset}){s->setSliderStyle(juce::Slider::LinearHorizontal);s->setTextBoxStyle(juce::Slider::TextBoxRight,false,62,22);}
    seek.setRange(0.0,1.0,.001);startOffset.setRange(0.0,1.0,.01);loopStart.setRange(0.0,1.0,.01);loopEnd.setRange(0.0,1.0,.01);seek.setTooltip("Posizione reference");startOffset.setTooltip("Start offset (secondi)");loopStart.setTooltip("Marker A (secondi)");loopEnd.setTooltip("Marker B (secondi)");fade.setTooltip("Crossfade A/B (ms)");hpf.setTooltip("High Pass (Hz)");bellFreq.setTooltip("Bell frequency (Hz)");bellGain.setTooltip("Bell gain (dB)");bellQ.setTooltip("Bell Q");lpf.setTooltip("Low Pass (Hz)");
    autoMatchAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"autoMatch",autoMatch);matchModeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"matchMode",matchMode);syncModeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"syncMode",syncMode);manualGainAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"manualGain",manualGain);
    eqBypassAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"eqBypass",eqBypass);listeningModeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"mode",listeningMode);fadeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"fade",fade);hpfAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"hpf",hpf);bellFreqAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"bellFreq",bellFreq);bellGainAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"bellGain",bellGain);bellQAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"bellQ",bellQ);lpfAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"lpf",lpf);
    transportSyncAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"transportSync",transportSync);syncOffsetAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"syncOffset",syncOffset);syncOffset.setTooltip("Offset rispetto alla DAW (secondi)");
    matchBypassAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"matchBypass",matchBypass);safeExportAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"safe",safeExport);resetMeters.onClick=[this]{p.resetMeters();};freezeDisplay.onClick=[this]{analysisDisplay.setFrozen(freezeDisplay.getToggleState());};
    hpfEnabledAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"hpfEnabled",hpfEnabled);bellEnabledAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"bellEnabled",bellEnabled);lpfEnabledAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"lpfEnabled",lpfEnabled);hpfSlopeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"hpfSlope",hpfSlope);lpfSlopeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"lpfSlope",lpfSlope);
    fftSizeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"fftOrder",fftSize);displayRateAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"displayRate",displayRate);fftSmoothingAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"fftSmoothing",fftSmoothing);fftSize.onChange=[this]{analysisDisplay.setFftOrder(9+fftSize.getSelectedId());};displayRate.onChange=[this]{const int rates[]{15,30,60};analysisDisplay.setRefreshRate(rates[juce::jlimit(0,2,displayRate.getSelectedId()-1)]);};fftSmoothing.onValueChange=[this]{analysisDisplay.setSmoothing((float)fftSmoothing.getValue());};analysisDisplay.setFftOrder(9+fftSize.getSelectedId());analysisDisplay.setSmoothing((float)fftSmoothing.getValue());
    auto filterChanged=[this]{refreshLibrary();};search.onTextChange=filterChanged;filterArtist.onTextChange=filterChanged;filterGenre.onTextChange=filterChanged;filterKey.onTextChange=filterChanged;minBpm.onTextChange=filterChanged;maxBpm.onTextChange=filterChanged;favouritesOnly.onClick=filterChanged;sort.onChange=filterChanged;cacheSize.onChange=[this]{constexpr std::size_t mb=1024u*1024u;const std::size_t sizes[]{128u,256u,512u,1024u};p.getCacheManager().setMaximumBytes(sizes[(size_t)juce::jlimit(0,3,cacheSize.getSelectedId()-1)]*mb);list.repaint();};save.onClick=[this]{saveSelected();};remove.onClick=[this]{removeSelected();};play.onClick=[this]{p.playReference();};pause.onClick=[this]{p.pauseReference();};stop.onClick=[this]{p.stopReference();};mix.onClick=[this]{p.setReference(false);};ref.onClick=[this]{p.setReference(true);};seek.onDragEnd=[this]{p.getPlayer().seek(seek.getValue());};startOffset.onDragEnd=[this]{p.getPlayer().setStartOffset(startOffset.getValue());persistPlayback();};loopStart.onValueChange=[this]{applyLoop();};loopEnd.onValueChange=[this]{applyLoop();};loopStart.onDragEnd=[this]{persistPlayback();};loopEnd.onDragEnd=[this]{persistPlayback();};loopEnabled.onClick=[this]{applyLoop();persistPlayback();};
    add.onClick=[this]{auto chooser=std::make_shared<juce::FileChooser>("Scegli reference",juce::File{},"*.wav;*.aiff;*.aif;*.flac;*.mp3");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this,chooser](const juce::FileChooser&f){if(f.getResult().existsAsFile()){juce::Component::SafePointer<ReferenceLabEditor>safe(this);p.loadFileAsync(f.getResult(),[safe](const juce::String&error){if(safe){if(error.isNotEmpty())safe->showError(error);safe->refreshLibrary();}});}});};
    scan.onClick=[this]{chooseFolder();};importCatalog.onClick=[this]{chooseCatalog();};addUrl.onClick=[this]{auto*w=new juce::AlertWindow("Aggiungi reference remota","Inserisci un URL diretto HTTP/HTTPS a un file audio",juce::MessageBoxIconType::QuestionIcon);w->addTextEditor("url","","URL");w->addButton("Aggiungi",1,juce::KeyPress(juce::KeyPress::returnKey));w->addButton("Annulla",0,juce::KeyPress(juce::KeyPress::escapeKey));w->enterModalState(true,juce::ModalCallbackFunction::create([this,w](int result){std::unique_ptr<juce::AlertWindow>owner(w);if(result==1){juce::String error;if(!p.getReferenceManager().addUrl(w->getTextEditorContents("url"),error))showError(error);refreshLibrary();}}),false);};
    newPlaylist.onClick=[this]{auto*w=new juce::AlertWindow("Nuova playlist","Scegli un nome",juce::MessageBoxIconType::QuestionIcon);w->addTextEditor("name","","Nome");w->addButton("Crea",1,juce::KeyPress(juce::KeyPress::returnKey));w->addButton("Annulla",0,juce::KeyPress(juce::KeyPress::escapeKey));w->enterModalState(true,juce::ModalCallbackFunction::create([this,w](int result){std::unique_ptr<juce::AlertWindow>owner(w);if(result==1){juce::String error;if(!p.getReferenceManager().createPlaylist(w->getTextEditorContents("name"),error))showError(error);refreshPlaylists();}}),false);};
    addToPlaylist.onClick=[this]{auto row=list.getSelectedRow(),index=playlist.getSelectedItemIndex();if(row<0||index<0||index>=(int)playlistRows.size())return;juce::String error;if(!p.getReferenceManager().addToPlaylist(playlistRows[(size_t)index].id,rows[(size_t)row].uuid,error))showError(error);refreshPlaylists();};
    auto navigate=[this](int delta){auto index=playlist.getSelectedItemIndex();if(index<0||index>=(int)playlistRows.size())return;juce::String error;if(auto item=p.getReferenceManager().selectPlaylistRelative(playlistRows[(size_t)index].id,delta,error))playItem(*item);else showError(error);refreshPlaylists();};previousReference.onClick=[navigate]{navigate(-1);};nextReference.onClick=[navigate]{navigate(1);};refreshLibrary();refreshPlaylists();startTimerHz(20);
    relink.onClick=[this]{auto row=list.getSelectedRow();if(row<0||row>=getNumRows())return;auto chooser=std::make_shared<juce::FileChooser>("Ricollega reference",juce::File{},"*.wav;*.aiff;*.aif;*.flac;*.mp3");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this,chooser,row](const juce::FileChooser&f){if(f.getResult().existsAsFile()){juce::String error;if(!p.getReferenceManager().relink(rows[(size_t)row].uuid,f.getResult(),error))showError(error);refreshLibrary();}});};
    auto presetFolder=juce::File::getSpecialLocation(juce::File::userApplicationDataDirectory).getChildFile("ReferenceLab").getChildFile("Presets");
    savePreset.onClick=[this,presetFolder]{auto chooser=std::make_shared<juce::FileChooser>("Salva preset",presetFolder.getChildFile("Comparison.rlpreset"),"*.rlpreset");chooser->launchAsync(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::canSelectFiles|juce::FileBrowserComponent::warnAboutOverwriting,[this,chooser](const juce::FileChooser&f){if(f.getResult()!=juce::File{}){juce::String error;if(!p.saveComparisonPreset(f.getResult().withFileExtension("rlpreset"),error))showError(error);}});};
    loadPreset.onClick=[this,presetFolder]{auto chooser=std::make_shared<juce::FileChooser>("Carica preset",presetFolder,"*.rlpreset");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this,chooser](const juce::FileChooser&f){if(f.getResult().existsAsFile()){juce::String error;if(!p.loadComparisonPreset(f.getResult(),error))showError(error);}});};
}
void ReferenceLabEditor::refreshLibrary(){referencelab::ReferenceFilter f;f.query=search.getText();f.artist=filterArtist.getText();f.genre=filterGenre.getText();f.musicalKey=filterKey.getText();f.minimumBpm=minBpm.getText().isEmpty()?0:minBpm.getText().getDoubleValue();f.maximumBpm=maxBpm.getText().isEmpty()?999:maxBpm.getText().getDoubleValue();f.favouritesOnly=favouritesOnly.getToggleState();f.sort=static_cast<referencelab::ReferenceSort>(juce::jmax(0,sort.getSelectedId()-1));rows=p.getReferenceManager().filter(f);list.updateContent();list.repaint();}
void ReferenceLabEditor::refreshPlaylists(){auto selected=playlist.getText();playlistRows=p.getReferenceManager().playlistsSnapshot();playlist.clear(juce::dontSendNotification);for(size_t i=0;i<playlistRows.size();++i)playlist.addItem(playlistRows[i].name+" ("+juce::String(playlistRows[i].referenceIds.size())+")",(int)i+1);for(size_t i=0;i<playlistRows.size();++i)if(playlistRows[i].name==selected.upToFirstOccurrenceOf(" (",false,false)){playlist.setSelectedItemIndex((int)i,juce::dontSendNotification);return;}if(!playlistRows.empty())playlist.setSelectedItemIndex(0,juce::dontSendNotification);}
void ReferenceLabEditor::showError(const juce::String&e){juce::NativeMessageBox::showMessageBoxAsync(juce::MessageBoxIconType::WarningIcon,"ReferenceLab",e);}
void ReferenceLabEditor::chooseFolder(){auto chooser=std::make_shared<juce::FileChooser>("Cartella reference");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectDirectories,[this,chooser](const juce::FileChooser&f){if(f.getResult().isDirectory()){juce::String warning;p.getReferenceManager().scanFolder(f.getResult(),recursiveScan.getToggleState(),warning);if(warning.isNotEmpty())showError(warning);refreshLibrary();}});}
void ReferenceLabEditor::chooseCatalog(){auto chooser=std::make_shared<juce::FileChooser>("Importa catalogo JSON",juce::File{},"*.json");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this,chooser](const juce::FileChooser&f){if(f.getResult().existsAsFile()){juce::String warning;auto added=p.getReferenceManager().importCatalog(f.getResult(),warning);if(warning.isNotEmpty())showError(warning);else if(added==0)showError("Il catalogo non contiene nuove reference");refreshLibrary();}});}
void ReferenceLabEditor::paintListBoxItem(int row,juce::Graphics&g,int w,int h,bool selected){if(row<0||row>=getNumRows())return;if(selected)g.fillAll(juce::Colour(0xff315b78));auto&item=rows[(size_t)row];auto remote=item.source.startsWithIgnoreCase("http://")||item.source.startsWithIgnoreCase("https://");auto lib=p.getReferenceManager().snapshot();auto file=item.resolveAgainst(lib.root);auto state=p.getCacheManager().getState(file);juce::String badge=remote?"[WEB] ":state==referencelab::CacheState::cached?"[CACHE] ":state==referencelab::CacheState::loading?"[LOAD] ":state==referencelab::CacheState::error?"[ERR] ":"";g.setColour(remote||file.existsAsFile()?juce::Colours::white:juce::Colours::orangered);g.drawText(badge+item.title+"  -  "+item.artist,10,0,w-20,h,juce::Justification::centredLeft,true);}
void ReferenceLabEditor::listBoxItemDoubleClicked(int row,const juce::MouseEvent&){if(row<0||row>=getNumRows())return;configurePlayback(row);playItem(rows[(size_t)row]);}
void ReferenceLabEditor::playItem(const referencelab::ReferenceMetadata&item){p.getPlayer().setStartOffset(item.startOffsetSeconds);p.getPlayer().setLoop(item.loop.enabled,item.loop.startSeconds,item.loop.endSeconds,item.loop.crossfadeMs);auto remote=item.source.startsWithIgnoreCase("http://")||item.source.startsWithIgnoreCase("https://");auto file=item.resolveAgainst(p.getReferenceManager().snapshot().root);juce::Component::SafePointer<ReferenceLabEditor>safe(this);auto completed=[safe](const juce::String&error){if(!safe)return;if(error.isNotEmpty())safe->showError(error);else safe->p.setReference(true);safe->list.repaint();};if(remote)p.loadUrlAsync(juce::URL(item.source),std::move(completed));else p.loadFileAsync(file,std::move(completed));list.repaint();}
void ReferenceLabEditor::selectedRowsChanged(int row){if(row<0||row>=getNumRows())return;auto&m=rows[(size_t)row];editTitle.setText(m.title,false);editArtist.setText(m.artist,false);editAlbum.setText(m.album,false);editGenre.setText(m.genre,false);editYear.setText(m.year?juce::String(*m.year):juce::String{},false);editBpm.setText(m.bpm?juce::String(*m.bpm,2):juce::String{},false);editKey.setText(m.musicalKey,false);editRating.setText(m.rating?juce::String(*m.rating):juce::String{},false);editTags.setText(m.tags.joinIntoString(", "),false);editNotes.setText(m.notes,false);editFavourite.setToggleState(m.favourite,juce::dontSendNotification);const double duration=juce::jmax(1.0,m.durationSeconds);for(auto*s:{&seek,&startOffset,&loopStart,&loopEnd})s->setRange(0.0,duration,.01);startOffset.setValue(m.startOffsetSeconds,juce::dontSendNotification);loopStart.setValue(m.loop.startSeconds,juce::dontSendNotification);loopEnd.setValue(m.loop.endSeconds,juce::dontSendNotification);loopEnabled.setToggleState(m.loop.enabled,juce::dontSendNotification);}
void ReferenceLabEditor::configurePlayback(int row){if(row<0||row>=getNumRows())return;auto&m=rows[(size_t)row];p.getPlayer().setStartOffset(m.startOffsetSeconds);p.getPlayer().setLoop(m.loop.enabled,m.loop.startSeconds,m.loop.endSeconds,m.loop.crossfadeMs);waveform.setLoop(m.loop.enabled,m.loop.startSeconds,m.loop.endSeconds);}
void ReferenceLabEditor::applyLoop(){p.getPlayer().setLoop(loopEnabled.getToggleState(),loopStart.getValue(),loopEnd.getValue());waveform.setLoop(loopEnabled.getToggleState(),loopStart.getValue(),loopEnd.getValue());}
void ReferenceLabEditor::persistPlayback(){auto row=list.getSelectedRow();if(row<0||row>=getNumRows())return;auto item=rows[(size_t)row];item.startOffsetSeconds=startOffset.getValue();item.loop.enabled=loopEnabled.getToggleState();item.loop.startSeconds=loopStart.getValue();item.loop.endSeconds=loopEnd.getValue();if(item.loop.enabled&&!item.loop.isValid()){showError("Il marker B deve essere successivo al marker A");return;}juce::String error;if(!p.getReferenceManager().updateMetadata(item,error))showError(error);else rows[(size_t)row]=std::move(item);}
void ReferenceLabEditor::saveSelected(){const int row=list.getSelectedRow();if(row<0||row>=getNumRows())return;auto item=rows[(size_t)row];item.title=editTitle.getText().trim();item.artist=editArtist.getText().trim();item.album=editAlbum.getText().trim();item.genre=editGenre.getText().trim();item.musicalKey=editKey.getText().trim();item.notes=editNotes.getText();item.favourite=editFavourite.getToggleState();item.tags=juce::StringArray::fromTokens(editTags.getText(),",","\"");item.tags.trim();item.tags.removeEmptyStrings();const auto bpm=editBpm.getText().trim();const auto year=editYear.getText().trim();const auto rating=editRating.getText().trim();item.bpm=bpm.isEmpty()?std::nullopt:std::optional<double>(bpm.getDoubleValue());item.year=year.isEmpty()?std::nullopt:std::optional<int>(year.getIntValue());item.rating=rating.isEmpty()?std::nullopt:std::optional<int>(rating.getIntValue());juce::String error;if(!p.getReferenceManager().updateMetadata(item,error))showError(error);refreshLibrary();}
void ReferenceLabEditor::removeSelected(){auto row=list.getSelectedRow();if(row<0||row>=getNumRows())return;juce::String error;if(!p.getReferenceManager().remove(rows[(size_t)row].uuid,error))showError(error);refreshLibrary();}
void ReferenceLabEditor::timerCallback(){auto text=[](const char*name,const referencelab::MeterSnapshot&m){return juce::String(name)+"  LUFS "+juce::String(m.shortTermLufs,1)+"  Peak "+juce::String(m.peakDb,1)+"  TP "+juce::String(m.truePeakDbtp,1)+"  RMS "+juce::String(m.rmsDb,1)+"  Crest "+juce::String(m.crestDb,1)+"  DR "+juce::String(m.dynamicRangeDb,1);};mixMeters.setText(text("MIX",p.getMixMeters()),juce::dontSendNotification);referenceMeters.setText(text("REF",p.getReferenceMeters()),juce::dontSendNotification);auto o=p.getOutputMeters();outputMeters.setText("OUT  Corr "+juce::String(o.correlation,2)+"  Width "+juce::String(o.stereoWidth,2),juce::dontSendNotification);matchedGain.setText("Applied "+juce::String(p.getMatchedGainDb(),1)+" dB",juce::dontSendNotification);transportStatus.setText(transportSync.getToggleState()?(p.isTransportAvailable()?"DAW OK":"DAW N/A"):"FREE",juce::dontSendNotification);if(!seek.isMouseButtonDown())seek.setValue(p.getPlayer().getPositionSeconds(),juce::dontSendNotification);list.repaint();}
void ReferenceLabEditor::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff10151d));g.setColour(juce::Colour(0xff263241));g.fillRoundedRectangle(getLocalBounds().reduced(16).toFloat(),10);}
bool ReferenceLabEditor::keyPressed(const juce::KeyPress&key){if(key.getTextCharacter()=='b'||key.getTextCharacter()=='B'){p.setReference(!p.isReference());return true;}if(key==juce::KeyPress::spaceKey){p.getPlayer().isPlaying()?p.pauseReference():p.playReference();return true;}return false;}
void ReferenceLabEditor::resized(){
    p.state.state.setProperty("uiWidth",getWidth(),nullptr);p.state.state.setProperty("uiHeight",getHeight(),nullptr);auto r=getLocalBounds().reduced(28);title.setBounds(r.removeFromTop(38));
    auto bar=r.removeFromTop(36);add.setBounds(bar.removeFromLeft(105));scan.setBounds(bar.removeFromLeft(120).reduced(3,0));importCatalog.setBounds(bar.removeFromLeft(100).reduced(3,0));addUrl.setBounds(bar.removeFromLeft(95).reduced(3,0));remove.setBounds(bar.removeFromLeft(70).reduced(3,0));relink.setBounds(bar.removeFromLeft(70).reduced(3,0));savePreset.setBounds(bar.removeFromLeft(85).reduced(3,0));loadPreset.setBounds(bar.removeFromLeft(85).reduced(3,0));resetMeters.setBounds(bar.removeFromLeft(82).reduced(3,0));freezeDisplay.setBounds(bar.removeFromLeft(60));safeExport.setBounds(bar.removeFromLeft(82));ref.setBounds(bar.removeFromRight(95));mix.setBounds(bar.removeFromRight(65));
    auto filters=r.removeFromTop(36);search.setBounds(filters.removeFromLeft(260));favouritesOnly.setBounds(filters.removeFromLeft(115));sort.setBounds(filters.removeFromLeft(110));cacheSize.setBounds(filters.removeFromLeft(125).reduced(4,0));playlist.setBounds(filters.removeFromLeft(170).reduced(3,0));newPlaylist.setBounds(filters.removeFromLeft(60).reduced(2,0));addToPlaylist.setBounds(filters.removeFromLeft(80).reduced(2,0));previousReference.setBounds(filters.removeFromLeft(34).reduced(2,0));nextReference.setBounds(filters.removeFromLeft(34).reduced(2,0));
    auto dedicated=r.removeFromTop(34);filterArtist.setBounds(dedicated.removeFromLeft(170));filterGenre.setBounds(dedicated.removeFromLeft(150).reduced(3,0));filterKey.setBounds(dedicated.removeFromLeft(100).reduced(3,0));minBpm.setBounds(dedicated.removeFromLeft(90).reduced(3,0));maxBpm.setBounds(dedicated.removeFromLeft(90).reduced(3,0));recursiveScan.setBounds(dedicated.removeFromLeft(130));
    auto bottom=r.removeFromBottom(340);auto metadata=bottom.removeFromTop(108);auto line=metadata.removeFromTop(34);editTitle.setBounds(line.removeFromLeft(190));editArtist.setBounds(line.removeFromLeft(170).reduced(3,0));editAlbum.setBounds(line.removeFromLeft(170).reduced(3,0));editGenre.setBounds(line.removeFromLeft(130).reduced(3,0));editYear.setBounds(line.removeFromLeft(75).reduced(3,0));editBpm.setBounds(line.removeFromLeft(80).reduced(3,0));editKey.setBounds(line.removeFromLeft(85).reduced(3,0));editRating.setBounds(line.removeFromLeft(85).reduced(3,0));auto line2=metadata.removeFromTop(34);editTags.setBounds(line2.removeFromLeft(390));editNotes.setBounds(line2.removeFromLeft(380).reduced(3,0));editFavourite.setBounds(line2.removeFromLeft(100));save.setBounds(line2.removeFromLeft(130));
    auto playerLine=bottom.removeFromTop(38);play.setBounds(playerLine.removeFromLeft(64));pause.setBounds(playerLine.removeFromLeft(68).reduced(3,0));stop.setBounds(playerLine.removeFromLeft(64).reduced(3,0));seek.setBounds(playerLine.removeFromLeft(250));startOffset.setBounds(playerLine.removeFromLeft(170));loopEnabled.setBounds(playerLine.removeFromLeft(62));loopStart.setBounds(playerLine.removeFromLeft(135));loopEnd.setBounds(playerLine.removeFromLeft(135));
    auto match=bottom.removeFromTop(36);matchBypass.setBounds(match.removeFromLeft(105));autoMatch.setBounds(match.removeFromLeft(90));matchMode.setBounds(match.removeFromLeft(110));manualGain.setBounds(match.removeFromLeft(155));matchedGain.setBounds(match.removeFromLeft(90));transportSync.setBounds(match.removeFromLeft(78));syncMode.setBounds(match.removeFromLeft(125));syncOffset.setBounds(match.removeFromLeft(145));transportStatus.setBounds(match.removeFromLeft(65));
    auto eq1=bottom.removeFromTop(36);eqBypass.setBounds(eq1.removeFromLeft(100));listeningMode.setBounds(eq1.removeFromLeft(105));fade.setBounds(eq1.removeFromLeft(165));hpfEnabled.setBounds(eq1.removeFromLeft(55));hpf.setBounds(eq1.removeFromLeft(160));hpfSlope.setBounds(eq1.removeFromLeft(105));lpfEnabled.setBounds(eq1.removeFromLeft(55));lpf.setBounds(eq1.removeFromLeft(160));lpfSlope.setBounds(eq1.removeFromLeft(105));
    auto eq2=bottom.removeFromTop(36);bellEnabled.setBounds(eq2.removeFromLeft(65));bellFreq.setBounds(eq2.removeFromLeft(190));bellGain.setBounds(eq2.removeFromLeft(180));bellQ.setBounds(eq2.removeFromLeft(170));fftSize.setBounds(eq2.removeFromLeft(105));fftSmoothing.setBounds(eq2.removeFromLeft(170));displayRate.setBounds(eq2.removeFromLeft(90));
    mixMeters.setBounds(bottom.removeFromTop(24));referenceMeters.setBounds(bottom.removeFromTop(24));outputMeters.setBounds(bottom.removeFromTop(24));
    r.removeFromTop(8);auto library=r.removeFromLeft((int)(r.getWidth()*.42f));list.setBounds(library);r.removeFromLeft(8);waveform.setBounds(r.removeFromTop(105).reduced(0,3));analysisDisplay.setBounds(r);
}
