#include "PluginEditor.h"
ReferenceLabEditor::ReferenceLabEditor(ReferenceLabAudioProcessor&x):AudioProcessorEditor(x),p(x),analysisDisplay(x.getMixFifo(),x.getReferenceFifo(),x.getOutputFifo()){
    setResizable(true,true);setWantsKeyboardFocus(true);setResizeLimits(900,650,1800,1200);setSize(1100,780);
    addAndMakeVisible(add);
    addAndMakeVisible(scan);
    addAndMakeVisible(remove);
    addAndMakeVisible(save);
    addAndMakeVisible(savePreset);addAndMakeVisible(loadPreset);
    addAndMakeVisible(resetMeters);addAndMakeVisible(freezeDisplay);addAndMakeVisible(safeExport);addAndMakeVisible(matchBypass);
    addAndMakeVisible(mix);
    addAndMakeVisible(ref);
    addAndMakeVisible(play);
    addAndMakeVisible(pause);
    addAndMakeVisible(stop);
    addAndMakeVisible(title);
    addAndMakeVisible(search);
    addAndMakeVisible(favouritesOnly);
    addAndMakeVisible(editFavourite);
    addAndMakeVisible(sort);
    addAndMakeVisible(cacheSize);
    addAndMakeVisible(autoMatch);
    addAndMakeVisible(matchMode);
    addAndMakeVisible(manualGain);
    addAndMakeVisible(loopEnabled);addAndMakeVisible(eqBypass);addAndMakeVisible(listeningMode);
    addAndMakeVisible(hpfEnabled);addAndMakeVisible(bellEnabled);addAndMakeVisible(lpfEnabled);addAndMakeVisible(hpfSlope);addAndMakeVisible(lpfSlope);
    addAndMakeVisible(transportSync);addAndMakeVisible(transportStatus);
    for(auto*s:{&seek,&startOffset,&loopStart,&loopEnd,&fade,&hpf,&bellFreq,&bellGain,&bellQ,&lpf,&syncOffset})addAndMakeVisible(s);
    addAndMakeVisible(mixMeters);addAndMakeVisible(referenceMeters);addAndMakeVisible(outputMeters);addAndMakeVisible(matchedGain);
    addAndMakeVisible(editTitle);
    addAndMakeVisible(editArtist);
    addAndMakeVisible(editGenre);
    addAndMakeVisible(editBpm);
    addAndMakeVisible(editTags);
    addAndMakeVisible(list);
    addAndMakeVisible(analysisDisplay);
    title.setText("ReferenceLab 1.0",juce::dontSendNotification);search.setTextToShowWhenEmpty("Cerca titolo, artista, album, genere, tag...",juce::Colours::grey);
    editTitle.setTextToShowWhenEmpty("Titolo",juce::Colours::grey);editArtist.setTextToShowWhenEmpty("Artista",juce::Colours::grey);editGenre.setTextToShowWhenEmpty("Genere",juce::Colours::grey);editBpm.setTextToShowWhenEmpty("BPM",juce::Colours::grey);editTags.setTextToShowWhenEmpty("Tag separati da virgola",juce::Colours::grey);
    sort.addItemList({"Titolo","Artista","Genere","BPM","Rating","Data aggiunta","Ultimo uso"},1);sort.setSelectedId(1,juce::dontSendNotification);
    cacheSize.addItemList({"Cache 128 MB","Cache 256 MB","Cache 512 MB","Cache 1024 MB"},1);cacheSize.setSelectedId(3,juce::dontSendNotification);
    matchMode.addItemList({"Integrated","Short-Term","Momentary"},1);manualGain.setSliderStyle(juce::Slider::LinearHorizontal);manualGain.setTextBoxStyle(juce::Slider::TextBoxRight,false,64,24);manualGain.setTextValueSuffix(" dB");
    listeningMode.addItemList({"Stereo","Mono","Mid","Side"},1);
    hpfSlope.addItemList({"12 dB/oct","24 dB/oct"},1);lpfSlope.addItemList({"12 dB/oct","24 dB/oct"},1);
    for(auto*s:{&seek,&startOffset,&loopStart,&loopEnd,&fade,&hpf,&bellFreq,&bellGain,&bellQ,&lpf,&syncOffset}){s->setSliderStyle(juce::Slider::LinearHorizontal);s->setTextBoxStyle(juce::Slider::TextBoxRight,false,62,22);}
    seek.setRange(0.0,1.0,.001);startOffset.setRange(0.0,1.0,.01);loopStart.setRange(0.0,1.0,.01);loopEnd.setRange(0.0,1.0,.01);seek.setTooltip("Posizione reference");startOffset.setTooltip("Start offset (secondi)");loopStart.setTooltip("Marker A (secondi)");loopEnd.setTooltip("Marker B (secondi)");fade.setTooltip("Crossfade A/B (ms)");hpf.setTooltip("High Pass (Hz)");bellFreq.setTooltip("Bell frequency (Hz)");bellGain.setTooltip("Bell gain (dB)");bellQ.setTooltip("Bell Q");lpf.setTooltip("Low Pass (Hz)");
    autoMatchAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"autoMatch",autoMatch);matchModeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"matchMode",matchMode);manualGainAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"manualGain",manualGain);
    eqBypassAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"eqBypass",eqBypass);listeningModeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"mode",listeningMode);fadeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"fade",fade);hpfAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"hpf",hpf);bellFreqAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"bellFreq",bellFreq);bellGainAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"bellGain",bellGain);bellQAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"bellQ",bellQ);lpfAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"lpf",lpf);
    transportSyncAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"transportSync",transportSync);syncOffsetAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"syncOffset",syncOffset);syncOffset.setTooltip("Offset rispetto alla DAW (secondi)");
    matchBypassAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"matchBypass",matchBypass);safeExportAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"safe",safeExport);resetMeters.onClick=[this]{p.resetMeters();};freezeDisplay.onClick=[this]{analysisDisplay.setFrozen(freezeDisplay.getToggleState());};
    hpfEnabledAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"hpfEnabled",hpfEnabled);bellEnabledAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"bellEnabled",bellEnabled);lpfEnabledAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"lpfEnabled",lpfEnabled);hpfSlopeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"hpfSlope",hpfSlope);lpfSlopeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"lpfSlope",lpfSlope);
    search.onTextChange=[this]{refreshLibrary();};favouritesOnly.onClick=[this]{refreshLibrary();};sort.onChange=[this]{refreshLibrary();};cacheSize.onChange=[this]{constexpr std::size_t mb=1024u*1024u;const std::size_t sizes[]{128u,256u,512u,1024u};p.getCacheManager().setMaximumBytes(sizes[(size_t)juce::jlimit(0,3,cacheSize.getSelectedId()-1)]*mb);list.repaint();};save.onClick=[this]{saveSelected();};remove.onClick=[this]{removeSelected();};play.onClick=[this]{p.playReference();};pause.onClick=[this]{p.pauseReference();};stop.onClick=[this]{p.stopReference();};mix.onClick=[this]{p.setReference(false);};ref.onClick=[this]{p.setReference(true);};seek.onDragEnd=[this]{p.getPlayer().seek(seek.getValue());};startOffset.onDragEnd=[this]{p.getPlayer().setStartOffset(startOffset.getValue());persistPlayback();};loopStart.onValueChange=[this]{applyLoop();};loopEnd.onValueChange=[this]{applyLoop();};loopStart.onDragEnd=[this]{persistPlayback();};loopEnd.onDragEnd=[this]{persistPlayback();};loopEnabled.onClick=[this]{applyLoop();persistPlayback();};
    add.onClick=[this]{auto chooser=std::make_shared<juce::FileChooser>("Scegli reference",juce::File{},"*.wav;*.aiff;*.aif;*.flac;*.mp3");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this,chooser](const juce::FileChooser&f){if(f.getResult().existsAsFile()){juce::Component::SafePointer<ReferenceLabEditor>safe(this);p.loadFileAsync(f.getResult(),[safe](const juce::String&error){if(safe){if(error.isNotEmpty())safe->showError(error);safe->refreshLibrary();}});}});};
    scan.onClick=[this]{chooseFolder();};refreshLibrary();startTimerHz(20);
    auto presetFolder=juce::File::getSpecialLocation(juce::File::userApplicationDataDirectory).getChildFile("ReferenceLab").getChildFile("Presets");
    savePreset.onClick=[this,presetFolder]{auto chooser=std::make_shared<juce::FileChooser>("Salva preset",presetFolder.getChildFile("Comparison.rlpreset"),"*.rlpreset");chooser->launchAsync(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::canSelectFiles|juce::FileBrowserComponent::warnAboutOverwriting,[this,chooser](const juce::FileChooser&f){if(f.getResult()!=juce::File{}){juce::String error;if(!p.saveComparisonPreset(f.getResult().withFileExtension("rlpreset"),error))showError(error);}});};
    loadPreset.onClick=[this,presetFolder]{auto chooser=std::make_shared<juce::FileChooser>("Carica preset",presetFolder,"*.rlpreset");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this,chooser](const juce::FileChooser&f){if(f.getResult().existsAsFile()){juce::String error;if(!p.loadComparisonPreset(f.getResult(),error))showError(error);}});};
}
void ReferenceLabEditor::refreshLibrary(){referencelab::ReferenceFilter f;f.query=search.getText();f.favouritesOnly=favouritesOnly.getToggleState();f.sort=static_cast<referencelab::ReferenceSort>(juce::jmax(0,sort.getSelectedId()-1));rows=p.getReferenceManager().filter(f);list.updateContent();list.repaint();}
void ReferenceLabEditor::showError(const juce::String&e){juce::NativeMessageBox::showMessageBoxAsync(juce::MessageBoxIconType::WarningIcon,"ReferenceLab",e);}
void ReferenceLabEditor::chooseFolder(){auto chooser=std::make_shared<juce::FileChooser>("Cartella reference");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectDirectories,[this,chooser](const juce::FileChooser&f){if(f.getResult().isDirectory()){juce::String warning;p.getReferenceManager().scanFolder(f.getResult(),true,warning);if(warning.isNotEmpty())showError(warning);refreshLibrary();}});}
void ReferenceLabEditor::paintListBoxItem(int row,juce::Graphics&g,int w,int h,bool selected){if(row<0||row>=getNumRows())return;if(selected)g.fillAll(juce::Colour(0xff315b78));auto lib=p.getReferenceManager().snapshot();auto file=rows[(size_t)row].resolveAgainst(lib.root);auto state=p.getCacheManager().getState(file);juce::String badge=state==referencelab::CacheState::cached?"[CACHE] ":state==referencelab::CacheState::loading?"[LOAD] ":state==referencelab::CacheState::error?"[ERR] ":"";g.setColour(file.existsAsFile()?juce::Colours::white:juce::Colours::orangered);g.drawText(badge+rows[(size_t)row].title+"  -  "+rows[(size_t)row].artist,10,0,w-20,h,juce::Justification::centredLeft,true);}
void ReferenceLabEditor::listBoxItemDoubleClicked(int row,const juce::MouseEvent&){if(row<0||row>=getNumRows())return;configurePlayback(row);auto file=rows[(size_t)row].resolveAgainst(p.getReferenceManager().snapshot().root);juce::Component::SafePointer<ReferenceLabEditor>safe(this);p.loadFileAsync(file,[safe](const juce::String&error){if(!safe)return;if(error.isNotEmpty())safe->showError(error);else safe->p.setReference(true);safe->list.repaint();});list.repaint();}
void ReferenceLabEditor::selectedRowsChanged(int row){if(row<0||row>=getNumRows())return;auto&m=rows[(size_t)row];editTitle.setText(m.title,false);editArtist.setText(m.artist,false);editGenre.setText(m.genre,false);editBpm.setText(m.bpm?juce::String(*m.bpm,2):juce::String{},false);editTags.setText(m.tags.joinIntoString(", "),false);editFavourite.setToggleState(m.favourite,juce::dontSendNotification);auto duration=juce::jmax(1.0,m.durationSeconds);for(auto*s:{&seek,&startOffset,&loopStart,&loopEnd})s->setRange(0.0,duration,.01);startOffset.setValue(m.startOffsetSeconds,juce::dontSendNotification);loopStart.setValue(m.loop.startSeconds,juce::dontSendNotification);loopEnd.setValue(m.loop.endSeconds,juce::dontSendNotification);loopEnabled.setToggleState(m.loop.enabled,juce::dontSendNotification);}
void ReferenceLabEditor::configurePlayback(int row){if(row<0||row>=getNumRows())return;auto&m=rows[(size_t)row];p.getPlayer().setStartOffset(m.startOffsetSeconds);p.getPlayer().setLoop(m.loop.enabled,m.loop.startSeconds,m.loop.endSeconds,m.loop.crossfadeMs);}
void ReferenceLabEditor::applyLoop(){p.getPlayer().setLoop(loopEnabled.getToggleState(),loopStart.getValue(),loopEnd.getValue());}
void ReferenceLabEditor::persistPlayback(){auto row=list.getSelectedRow();if(row<0||row>=getNumRows())return;auto item=rows[(size_t)row];item.startOffsetSeconds=startOffset.getValue();item.loop.enabled=loopEnabled.getToggleState();item.loop.startSeconds=loopStart.getValue();item.loop.endSeconds=loopEnd.getValue();if(item.loop.enabled&&!item.loop.isValid()){showError("Il marker B deve essere successivo al marker A");return;}juce::String error;if(!p.getReferenceManager().updateMetadata(item,error))showError(error);else rows[(size_t)row]=std::move(item);}
void ReferenceLabEditor::saveSelected(){auto row=list.getSelectedRow();if(row<0||row>=getNumRows())return;auto item=rows[(size_t)row];item.title=editTitle.getText().trim();item.artist=editArtist.getText().trim();item.genre=editGenre.getText().trim();item.favourite=editFavourite.getToggleState();item.tags=juce::StringArray::fromTokens(editTags.getText(),",","\"");item.tags.trim();item.tags.removeEmptyStrings();auto bpm=editBpm.getText().trim();item.bpm=bpm.isEmpty()?std::nullopt:std::optional<double>(bpm.getDoubleValue());juce::String error;if(!p.getReferenceManager().updateMetadata(item,error))showError(error);refreshLibrary();}
void ReferenceLabEditor::removeSelected(){auto row=list.getSelectedRow();if(row<0||row>=getNumRows())return;juce::String error;if(!p.getReferenceManager().remove(rows[(size_t)row].uuid,error))showError(error);refreshLibrary();}
void ReferenceLabEditor::timerCallback(){auto text=[](const char*name,const referencelab::MeterSnapshot&m){return juce::String(name)+"  LUFS "+juce::String(m.shortTermLufs,1)+"  Peak "+juce::String(m.peakDb,1)+"  TP "+juce::String(m.truePeakDbtp,1)+"  RMS "+juce::String(m.rmsDb,1)+"  Crest "+juce::String(m.crestDb,1)+"  DR "+juce::String(m.dynamicRangeDb,1);};mixMeters.setText(text("MIX",p.getMixMeters()),juce::dontSendNotification);referenceMeters.setText(text("REF",p.getReferenceMeters()),juce::dontSendNotification);auto o=p.getOutputMeters();outputMeters.setText("OUT  Corr "+juce::String(o.correlation,2)+"  Width "+juce::String(o.stereoWidth,2),juce::dontSendNotification);matchedGain.setText("Applied "+juce::String(p.getMatchedGainDb(),1)+" dB",juce::dontSendNotification);transportStatus.setText(transportSync.getToggleState()?(p.isTransportAvailable()?"DAW OK":"DAW N/A"):"FREE",juce::dontSendNotification);if(!seek.isMouseButtonDown())seek.setValue(p.getPlayer().getPositionSeconds(),juce::dontSendNotification);list.repaint();}
void ReferenceLabEditor::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff10151d));g.setColour(juce::Colour(0xff263241));g.fillRoundedRectangle(getLocalBounds().reduced(16).toFloat(),10);}
bool ReferenceLabEditor::keyPressed(const juce::KeyPress&key){if(key.getTextCharacter()=='b'||key.getTextCharacter()=='B'){p.setReference(!p.isReference());return true;}if(key==juce::KeyPress::spaceKey){p.getPlayer().isPlaying()?p.pauseReference():p.playReference();return true;}return false;}
void ReferenceLabEditor::resized(){
    auto r=getLocalBounds().reduced(28);title.setBounds(r.removeFromTop(38));
    auto bar=r.removeFromTop(36);add.setBounds(bar.removeFromLeft(120));scan.setBounds(bar.removeFromLeft(150).reduced(4,0));remove.setBounds(bar.removeFromLeft(82).reduced(4,0));savePreset.setBounds(bar.removeFromLeft(96).reduced(4,0));loadPreset.setBounds(bar.removeFromLeft(96).reduced(4,0));resetMeters.setBounds(bar.removeFromLeft(96).reduced(4,0));freezeDisplay.setBounds(bar.removeFromLeft(70));safeExport.setBounds(bar.removeFromLeft(95));ref.setBounds(bar.removeFromRight(105));mix.setBounds(bar.removeFromRight(75));
    auto filters=r.removeFromTop(36);search.setBounds(filters.removeFromLeft(330));favouritesOnly.setBounds(filters.removeFromLeft(125));sort.setBounds(filters.removeFromLeft(130));cacheSize.setBounds(filters.removeFromLeft(140).reduced(4,0));
    auto bottom=r.removeFromBottom(304);auto metadata=bottom.removeFromTop(72);auto line=metadata.removeFromTop(34);editTitle.setBounds(line.removeFromLeft(230));editArtist.setBounds(line.removeFromLeft(210).reduced(4,0));editGenre.setBounds(line.removeFromLeft(150).reduced(4,0));editBpm.setBounds(line.removeFromLeft(90).reduced(4,0));auto line2=metadata.removeFromTop(36);editTags.setBounds(line2.removeFromLeft(400));editFavourite.setBounds(line2.removeFromLeft(100));save.setBounds(line2.removeFromLeft(130));
    auto playerLine=bottom.removeFromTop(38);play.setBounds(playerLine.removeFromLeft(64));pause.setBounds(playerLine.removeFromLeft(68).reduced(3,0));stop.setBounds(playerLine.removeFromLeft(64).reduced(3,0));seek.setBounds(playerLine.removeFromLeft(250));startOffset.setBounds(playerLine.removeFromLeft(170));loopEnabled.setBounds(playerLine.removeFromLeft(62));loopStart.setBounds(playerLine.removeFromLeft(135));loopEnd.setBounds(playerLine.removeFromLeft(135));
    auto match=bottom.removeFromTop(36);matchBypass.setBounds(match.removeFromLeft(115));autoMatch.setBounds(match.removeFromLeft(100));matchMode.setBounds(match.removeFromLeft(120));manualGain.setBounds(match.removeFromLeft(175));matchedGain.setBounds(match.removeFromLeft(105));transportSync.setBounds(match.removeFromLeft(85));syncOffset.setBounds(match.removeFromLeft(170));transportStatus.setBounds(match.removeFromLeft(70));
    auto eq1=bottom.removeFromTop(36);eqBypass.setBounds(eq1.removeFromLeft(100));listeningMode.setBounds(eq1.removeFromLeft(105));fade.setBounds(eq1.removeFromLeft(165));hpfEnabled.setBounds(eq1.removeFromLeft(55));hpf.setBounds(eq1.removeFromLeft(160));hpfSlope.setBounds(eq1.removeFromLeft(105));lpfEnabled.setBounds(eq1.removeFromLeft(55));lpf.setBounds(eq1.removeFromLeft(160));lpfSlope.setBounds(eq1.removeFromLeft(105));
    auto eq2=bottom.removeFromTop(36);bellEnabled.setBounds(eq2.removeFromLeft(65));bellFreq.setBounds(eq2.removeFromLeft(220));bellGain.setBounds(eq2.removeFromLeft(210));bellQ.setBounds(eq2.removeFromLeft(200));
    mixMeters.setBounds(bottom.removeFromTop(24));referenceMeters.setBounds(bottom.removeFromTop(24));outputMeters.setBounds(bottom.removeFromTop(24));
    r.removeFromTop(8);auto library=r.removeFromLeft((int)(r.getWidth()*.42f));list.setBounds(library);r.removeFromLeft(8);analysisDisplay.setBounds(r);
}
