#include "PluginEditor.h"
#include "UI/RemoteSourceDialog.h"
#include "UI/UiTheme.h"
namespace {constexpr int cacheSizesMb[]{128,256,512,1024};int cacheChoiceFor(int mb){for(int i=0;i<4;++i)if(cacheSizesMb[i]==mb)return i+1;return 3;}}
ReferenceLabEditor::ReferenceLabEditor(ReferenceLabAudioProcessor&x):AudioProcessorEditor(x),p(x),magicBuilder(std::make_unique<foleys::MagicGUIBuilder>(x.getGuiState())),analysisDisplay(x.getMixFifo(),x.getReferenceFifo(),x.getMixSideFifo(),x.getReferenceSideFifo(),x.getOutputFifo(),x.state),waveform(x.getPlayer()),eqCurve(x.getCompareMixMidFifo(),x.getCompareReferenceMidFifo(),x.getCompareMixSideFifo(),x.getCompareReferenceSideFifo(),x.state),airwindowsMeter(x.getAirwindowsMeterModel()){
    setResizable(true,true);setWantsKeyboardFocus(true);setResizeLimits(900,650,1800,1200);setSize(juce::jlimit(900,1800,(int)p.state.state.getProperty("uiWidth",1100)),juce::jlimit(650,1200,(int)p.state.state.getProperty("uiHeight",780)));
    magicBuilder->registerLookAndFeel("ReferenceLab",std::make_unique<referencelab::GuiMagicLookAndFeel>());
    libraryWidthRatio=juce::jlimit(.25,.55,(double)p.state.state.getProperty("uiLibraryWidthRatio",.34));libraryOpen=(bool)p.state.state.getProperty("uiLibraryOpen",true);settingsOpen=false;mainSplitter.setTooltip("Trascina per ridimensionare la libreria; doppio clic per ripristinare");mainSplitter.onDragStart=[this]{splitterDragStartRatio=libraryWidthRatio;};mainSplitter.onDrag=[this](int delta){auto available=juce::jmax(1,getWidth()-48);libraryWidthRatio=juce::jlimit(.25,.55,splitterDragStartRatio+(double)delta/available);p.state.state.setProperty("uiLibraryWidthRatio",libraryWidthRatio,nullptr);auto&tree=p.getGuiState().getGuiTree();referencelab::setGuiMagicLibraryRatio(tree,libraryWidthRatio);magicBuilder->updateLayout(magicSurface.getLocalBounds());};mainSplitter.onReset=[this]{libraryWidthRatio=.34;p.state.state.setProperty("uiLibraryWidthRatio",libraryWidthRatio,nullptr);auto&tree=p.getGuiState().getGuiTree();referencelab::setGuiMagicLibraryRatio(tree,libraryWidthRatio);magicBuilder->updateLayout(magicSurface.getLocalBounds());};
    analysisDisplay.setSampleRate(p.getSampleRate());
    for(auto*button:{&recursiveScan,&favouritesOnly,&sortDescending,&editFavourite,&autoMatch,&matchBypass,&freezeDisplay,&swapLR,&showMidSpectrum,&showSideSpectrum,&safeExport,&loopEnabled,&eqBypass,&hpfEnabled,&bellEnabled,&lpfEnabled,&transportSync})button->setClickingTogglesState(true);
    waveform.onSeek=[this](double value){seek.setValue(value,juce::dontSendNotification);};waveform.onLoopChanged=[this](double a,double b){loopStart.setValue(a,juce::dontSendNotification);loopEnd.setValue(b,juce::dontSendNotification);applyLoop();persistPlayback();};
    settingsButton.setButtonText(juce::String::charToString(0x2699));settingsButton.setTooltip("Impostazioni");libraryDrawer.setTooltip("Mostra o nasconde la libreria");title.setText("ReferenceLab 2.0",juce::dontSendNotification);search.setTextToShowWhenEmpty("Cerca titolo, artista, album, genere, tag...",juce::Colours::grey);mix.setTooltip("Ascolta il Mix (scorciatoia B)");ref.setTooltip("Ascolta la Reference (scorciatoia B)");transportStatus.setTooltip("Sorgente in ascolto, riproduzione Reference e sincronizzazione DAW");hostTempoStatus.setTooltip("Stato, posizione, BPM e metrica musicale comunicati dalla DAW");
    editTitle.setTextToShowWhenEmpty("Titolo",juce::Colours::grey);editArtist.setTextToShowWhenEmpty("Artista",juce::Colours::grey);editAlbum.setTextToShowWhenEmpty("Album",juce::Colours::grey);editGenre.setTextToShowWhenEmpty("Genere",juce::Colours::grey);editYear.setTextToShowWhenEmpty("Anno",juce::Colours::grey);editBpm.setTextToShowWhenEmpty("BPM",juce::Colours::grey);editKey.setTextToShowWhenEmpty("Tonalità",juce::Colours::grey);editRating.setTextToShowWhenEmpty("Rating 0-5",juce::Colours::grey);editTags.setTextToShowWhenEmpty("Tag separati da virgola",juce::Colours::grey);editNotes.setTextToShowWhenEmpty("Note",juce::Colours::grey);filterArtist.setTextToShowWhenEmpty("Filtro artista",juce::Colours::grey);filterGenre.setTextToShowWhenEmpty("Filtro genere",juce::Colours::grey);filterKey.setTextToShowWhenEmpty("Tonalità",juce::Colours::grey);minBpm.setTextToShowWhenEmpty("BPM min",juce::Colours::grey);maxBpm.setTextToShowWhenEmpty("BPM max",juce::Colours::grey);recursiveScan.setToggleState(true,juce::dontSendNotification);
    sort.addItemList({"Titolo","Artista","Album","Genere","Anno","BPM","Rating","Data aggiunta","Ultimo uso"},1);sort.setSelectedId(juce::jlimit(1,9,(int)p.state.state.getProperty("uiLibrarySort",1)),juce::dontSendNotification);sortDescending.setToggleState((bool)p.state.state.getProperty("uiLibrarySortDescending",false),juce::dontSendNotification);ratingFilter.addItemList({"Rating: tutti","Rating >= 1","Rating >= 2","Rating >= 3","Rating >= 4","Rating = 5"},1);ratingFilter.setSelectedId(juce::jlimit(1,6,(int)p.state.state.getProperty("uiMinimumRating",0)+1),juce::dontSendNotification);
    cacheSize.addItemList({"Cache 128 MB","Cache 256 MB","Cache 512 MB","Cache 1024 MB"},1);cacheSize.setSelectedId(cacheChoiceFor((int)p.state.state.getProperty("uiCacheMb",512)),juce::dontSendNotification);cacheStatus.setTooltip("Memoria RAM occupata dalle reference locali decodificate");clearCache.setTooltip("Libera la cache RAM senza interrompere la Reference in riproduzione");mixColourSelector.addItemList({"Mix: Azzurro","Mix: Arancione","Mix: Verde","Mix: Viola","Mix: Giallo","Mix: Rosso"},1);referenceColourSelector.addItemList({"Ref: Azzurro","Ref: Arancione","Ref: Verde","Ref: Viola","Ref: Giallo","Ref: Rosso"},1);mixColourSelector.setSelectedId(referencelab::UiTheme::paletteId(referencelab::UiTheme::mix(p.state.state)),juce::dontSendNotification);referenceColourSelector.setSelectedId(referencelab::UiTheme::paletteId(referencelab::UiTheme::reference(p.state.state)),juce::dontSendNotification);mixColourSelector.onChange=[this]{referencelab::UiTheme::setMix(p.state.state,referencelab::UiTheme::palette(mixColourSelector.getSelectedId()));applyTheme();};referenceColourSelector.onChange=[this]{referencelab::UiTheme::setReference(p.state.state,referencelab::UiTheme::palette(referenceColourSelector.getSelectedId()));applyTheme();};applyTheme();updateCacheStatus();
    matchMode.addItemList({"Integrated","Short-Term","Momentary"},1);manualGain.setSliderStyle(juce::Slider::LinearHorizontal);manualGain.setTextBoxStyle(juce::Slider::TextBoxRight,false,64,24);manualGain.setTextValueSuffix(" dB");
    syncMode.addItemList({"Timeline","Restart on Play"},1);listeningMode.addItemList({"Stereo","Mono","Mid","Side"},1);
    hpfSlope.addItemList({"12 dB/oct","24 dB/oct"},1);lpfSlope.addItemList({"12 dB/oct","24 dB/oct"},1);
    fftSize.addItemList({"FFT 1024","FFT 2048","FFT 4096","FFT 8192","FFT 16384","FFT 32768"},1);displayRate.addItemList({"15 Hz","30 Hz","60 Hz"},1);fftSmoothing.setSliderStyle(juce::Slider::LinearHorizontal);fftSmoothing.setTextBoxStyle(juce::Slider::TextBoxRight,false,55,22);analysisSlope.setTextValueSuffix(" dB/oct");analysisSlope.setTooltip("Compensazione grafica dello spettro FFT");swapLR.setTooltip("Scambia Left e Right su Mix e Reference");
    for(auto*s:{&seek,&startOffset,&loopStart,&loopEnd,&fade,&hpf,&bellFreq,&bellGain,&bellQ,&lpf,&syncOffset}){s->setSliderStyle(juce::Slider::LinearHorizontal);s->setTextBoxStyle(juce::Slider::TextBoxRight,false,62,22);}
    seek.setRange(0.0,1.0,.001);startOffset.setRange(0.0,1.0,.01);loopStart.setRange(0.0,1.0,.01);loopEnd.setRange(0.0,1.0,.01);seek.setTooltip("Posizione reference");startOffset.setTooltip("Start offset (secondi)");loopStart.setTooltip("Marker A (secondi)");loopEnd.setTooltip("Marker B (secondi)");fade.setTextValueSuffix(" ms");hpf.setTextValueSuffix(" Hz");bellFreq.setTextValueSuffix(" Hz");bellGain.setTextValueSuffix(" dB");lpf.setTextValueSuffix(" Hz");syncOffset.setTextValueSuffix(" s");fade.setTooltip("Crossfade A/B (ms)");hpf.setTooltip("High Pass (Hz)");bellFreq.setTooltip("Band Pass frequency (Hz)");bellGain.setTooltip("Band Pass gain (dB)");bellQ.setTooltip("Band Pass Q / bandwidth");lpf.setTooltip("Low Pass (Hz)");
    autoMatchAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"autoMatch",autoMatch);matchModeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"matchMode",matchMode);syncModeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"syncMode",syncMode);manualGainAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"manualGain",manualGain);
    eqBypassAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"eqBypass",eqBypass);listeningModeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"mode",listeningMode);fadeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"fade",fade);hpfAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"hpf",hpf);bellFreqAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"bellFreq",bellFreq);bellGainAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"bellGain",bellGain);bellQAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"bellQ",bellQ);lpfAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"lpf",lpf);
    transportSyncAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"transportSync",transportSync);syncOffsetAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"syncOffset",syncOffset);syncOffset.setTooltip("Offset rispetto alla DAW (secondi)");
    matchBypassAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"matchBypass",matchBypass);swapLRAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"swapLR",swapLR);showMidSpectrumAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"showMidSpectrum",showMidSpectrum);showSideSpectrumAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"showSideSpectrum",showSideSpectrum);safeExportAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"safe",safeExport);resetMeters.onClick=[this]{p.resetMeters();};freezeDisplay.onClick=[this]{analysisDisplay.setFrozen(freezeDisplay.getToggleState());};showMidSpectrum.onClick=[this]{analysisDisplay.repaint();};showSideSpectrum.onClick=[this]{analysisDisplay.repaint();};
    hpfEnabledAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"hpfEnabled",hpfEnabled);bellEnabledAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"bellEnabled",bellEnabled);lpfEnabledAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.state,"lpfEnabled",lpfEnabled);hpfSlopeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"hpfSlope",hpfSlope);lpfSlopeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"lpfSlope",lpfSlope);
    fftSizeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"fftOrder",fftSize);displayRateAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"displayRate",displayRate);fftSmoothingAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"fftSmoothing",fftSmoothing);analysisSlopeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.state,"analysisSlope",analysisSlope);fftSize.onChange=[this]{analysisDisplay.setFftOrder(9+fftSize.getSelectedId());};displayRate.onChange=[this]{const int rates[]{15,30,60};analysisDisplay.setRefreshRate(rates[juce::jlimit(0,2,displayRate.getSelectedId()-1)]);};fftSmoothing.onValueChange=[this]{analysisDisplay.setSmoothing((float)fftSmoothing.getValue());};analysisSlope.onValueChange=[this]{analysisDisplay.repaint();};analysisDisplay.setFftOrder(9+fftSize.getSelectedId());analysisDisplay.setSmoothing((float)fftSmoothing.getValue());
    auto filterChanged=[this]{refreshLibrary();};search.onTextChange=filterChanged;filterArtist.onTextChange=filterChanged;filterGenre.onTextChange=filterChanged;filterKey.onTextChange=filterChanged;minBpm.onTextChange=filterChanged;maxBpm.onTextChange=filterChanged;favouritesOnly.onClick=filterChanged;sort.onChange=[this]{p.state.state.setProperty("uiLibrarySort",sort.getSelectedId(),nullptr);refreshLibrary();};sortDescending.onClick=[this]{p.state.state.setProperty("uiLibrarySortDescending",sortDescending.getToggleState(),nullptr);refreshLibrary();};ratingFilter.onChange=[this]{p.state.state.setProperty("uiMinimumRating",juce::jmax(0,ratingFilter.getSelectedId()-1),nullptr);refreshLibrary();};cacheSize.onChange=[this]{auto id=juce::jlimit(1,4,cacheSize.getSelectedId());p.state.state.setProperty("uiCacheMb",cacheSizesMb[id-1],nullptr);updateCacheStatus();list.repaint();};clearCache.onClick=[this]{p.getCacheManager().clear();updateCacheStatus();list.repaint();};save.onClick=[this]{saveSelected();};remove.onClick=[this]{removeSelected();};play.onClick=[this]{p.playReference();};pause.onClick=[this]{p.pauseReference();};stop.onClick=[this]{p.stopReference();};mix.onClick=[this]{p.setReference(false);};ref.onClick=[this]{p.setReference(true);};seek.onDragEnd=[this]{p.getPlayer().seek(seek.getValue());};startOffset.onDragEnd=[this]{p.getPlayer().setStartOffset(startOffset.getValue());persistPlayback();};loopStart.onValueChange=[this]{applyLoop();};loopEnd.onValueChange=[this]{applyLoop();};loopStart.onDragEnd=[this]{persistPlayback();};loopEnd.onDragEnd=[this]{persistPlayback();};loopEnabled.onClick=[this]{applyLoop();persistPlayback();};resetWaveformView.onClick=[this]{waveform.resetView();};fullLoop.onClick=[this]{auto d=p.getPlayer().getDurationSeconds();if(d<=0){showError("Carica una reference prima di impostare il loop");return;}loopEnabled.setToggleState(true,juce::dontSendNotification);loopStart.setValue(0,juce::dontSendNotification);loopEnd.setValue(d,juce::dontSendNotification);applyLoop();persistPlayback();};
    add.onClick=[this]{auto chooser=std::make_shared<juce::FileChooser>("Scegli reference",juce::File{},"*.wav;*.aiff;*.aif;*.flac;*.mp3");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this,chooser](const juce::FileChooser&f){if(f.getResult().existsAsFile()){juce::Component::SafePointer<ReferenceLabEditor>safe(this);p.loadFileAsync(f.getResult(),[safe](const juce::String&error){if(safe){if(error.isNotEmpty())safe->showError(error);safe->refreshLibrary();}});}});};
    scan.onClick=[this]{chooseFolder();};importCatalog.onClick=[this]{chooseCatalog();};addUrl.onClick=[this]{juce::Component::SafePointer<ReferenceLabEditor>safe(this);referencelab::RemoteSourceDialog::show([safe](referencelab::RemoteSourceType type,const juce::String&text){if(!safe)return;if(type==referencelab::RemoteSourceType::jsonCatalog){safe->p.importCatalogUrlAsync(juce::URL(text),[safe](int added,const juce::String&error){if(!safe)return;if(error.isNotEmpty())safe->showError(error);else if(added==0)safe->showError("Il catalogo non contiene nuove reference");safe->refreshLibrary();});}else{juce::String error;if(!safe->p.getReferenceManager().addUrl(text,error))safe->showError(error);safe->refreshLibrary();}});};
    newPlaylist.onClick=[this]{auto*w=new juce::AlertWindow("Nuova playlist","Scegli un nome",juce::MessageBoxIconType::QuestionIcon);w->addTextEditor("name","","Nome");w->addButton("Crea",1,juce::KeyPress(juce::KeyPress::returnKey));w->addButton("Annulla",0,juce::KeyPress(juce::KeyPress::escapeKey));w->enterModalState(true,juce::ModalCallbackFunction::create([this,w](int result){std::unique_ptr<juce::AlertWindow>owner(w);if(result==1){juce::String error;if(!p.getReferenceManager().createPlaylist(w->getTextEditorContents("name"),error))showError(error);refreshPlaylists();}}),false);};
    addToPlaylist.onClick=[this]{auto row=list.getSelectedRow(),index=playlist.getSelectedItemIndex();if(row<0||index<0||index>=(int)playlistRows.size())return;juce::String error;if(!p.getReferenceManager().addToPlaylist(playlistRows[(size_t)index].id,rows[(size_t)row].uuid,error))showError(error);refreshPlaylists();};
    auto navigate=[this](int delta){auto index=playlist.getSelectedItemIndex();if(index<0||index>=(int)playlistRows.size())return;juce::String error;if(auto item=p.getReferenceManager().selectPlaylistRelative(playlistRows[(size_t)index].id,delta,error))playItem(*item);else showError(error);refreshPlaylists();};previousReference.onClick=[navigate]{navigate(-1);};nextReference.onClick=[navigate]{navigate(1);};refreshLibrary();refreshPlaylists();startTimerHz(20);
    relink.onClick=[this]{auto row=list.getSelectedRow();if(row<0||row>=getNumRows())return;auto chooser=std::make_shared<juce::FileChooser>("Ricollega reference",juce::File{},"*.wav;*.aiff;*.aif;*.flac;*.mp3");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this,chooser,row](const juce::FileChooser&f){if(f.getResult().existsAsFile()){juce::String error;if(!p.getReferenceManager().relink(rows[(size_t)row].uuid,f.getResult(),error))showError(error);refreshLibrary();}});};
    librarySelector.onChange=[this]{auto index=librarySelector.getSelectedItemIndex();if(index<0||index>=(int)libraryRows.size()||libraryRows[(size_t)index].id==p.getReferenceManager().activeLibraryId())return;juce::String error;if(!p.getReferenceManager().switchLibrary(libraryRows[(size_t)index].id,error))showError(error);refreshLibrary();refreshPlaylists();refreshLibraries();};newLibrary.onClick=[this]{auto chooser=std::make_shared<juce::FileChooser>("Scegli la cartella della nuova libreria");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectDirectories,[this,chooser](const juce::FileChooser&f){auto folder=f.getResult();if(folder.isDirectory()){juce::String error;if(!p.getReferenceManager().createLibrary(folder.getFileName(),folder,error))showError(error);refreshLibrary();refreshPlaylists();refreshLibraries();}});};
    refreshLibraries();auto presetFolder=juce::File::getSpecialLocation(juce::File::userApplicationDataDirectory).getChildFile("ReferenceLab").getChildFile("Presets");
    savePreset.onClick=[this,presetFolder]{auto chooser=std::make_shared<juce::FileChooser>("Salva preset",presetFolder.getChildFile("Comparison.rlpreset"),"*.rlpreset");chooser->launchAsync(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::canSelectFiles|juce::FileBrowserComponent::warnAboutOverwriting,[this,chooser](const juce::FileChooser&f){if(f.getResult()!=juce::File{}){juce::String error;if(!p.saveComparisonPreset(f.getResult().withFileExtension("rlpreset"),error))showError(error);}});};
    loadPreset.onClick=[this,presetFolder]{auto chooser=std::make_shared<juce::FileChooser>("Carica preset",presetFolder,"*.rlpreset");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this,chooser](const juce::FileChooser&f){if(f.getResult().existsAsFile()){juce::String error;if(!p.loadComparisonPreset(f.getResult(),error))showError(error);}});};
    libraryDrawer.onClick=[this]{libraryOpen=!libraryOpen;p.state.state.setProperty("uiLibraryOpen",libraryOpen,nullptr);auto&tree=p.getGuiState().getGuiTree();referencelab::setGuiMagicDrawers(tree,libraryOpen,settingsOpen,libraryWidthRatio);magicBuilder->updateLayout(magicSurface.getLocalBounds());};
    settingsButton.onClick=[this]{settingsOpen=!settingsOpen;auto&tree=p.getGuiState().getGuiTree();referencelab::setGuiMagicDrawers(tree,libraryOpen,settingsOpen,libraryWidthRatio);magicBuilder->updateLayout(magicSurface.getLocalBounds());};
    fileMenu.onClick=[this]{juce::PopupMenu menu;menu.addItem(1,"Aggiungi file audio...");menu.addItem(2,"Scansiona cartella...");menu.addItem(3,"Aggiungi sorgente web...");menu.addItem(4,"Importa catalogo JSON...");menu.addSeparator();menu.addItem(5,"Ricollega reference...");menu.addItem(6,"Rimuovi reference");juce::Component::SafePointer<ReferenceLabEditor>safe(this);menu.showMenuAsync(juce::PopupMenu::Options{}.withTargetComponent(fileMenu),[safe](int result){if(!safe)return;switch(result){case 1:safe->add.triggerClick();break;case 2:safe->scan.triggerClick();break;case 3:safe->addUrl.triggerClick();break;case 4:safe->importCatalog.triggerClick();break;case 5:safe->relink.triggerClick();break;case 6:safe->remove.triggerClick();break;default:break;}});};
    catalogMenu.onClick=[this]{juce::PopupMenu menu;menu.addItem(1,"Nuova libreria...");menu.addItem(2,"Nuova playlist...");menu.addItem(3,"Aggiungi selezione alla playlist");menu.addSeparator();menu.addItem(4,"Salva metadati");menu.addItem(5,"Salva preset confronto...");menu.addItem(6,"Carica preset confronto...");juce::Component::SafePointer<ReferenceLabEditor>safe(this);menu.showMenuAsync(juce::PopupMenu::Options{}.withTargetComponent(catalogMenu),[safe](int result){if(!safe)return;switch(result){case 1:safe->newLibrary.triggerClick();break;case 2:safe->newPlaylist.triggerClick();break;case 3:safe->addToPlaylist.triggerClick();break;case 4:safe->save.triggerClick();break;case 5:safe->savePreset.triggerClick();break;case 6:safe->loadPreset.triggerClick();break;default:break;}});};
    p.getGuiState().getPropertyAsValue("uiTab")=juce::jlimit(0,3,(int)p.state.state.getProperty("uiTab",0));
    p.getGuiState().setGuiValueTree(referencelab::createGuiMagicTheme(libraryWidthRatio));referencelab::setGuiMagicDrawers(p.getGuiState().getGuiTree(),libraryOpen,settingsOpen,libraryWidthRatio);
    magicComponents={
        {"libraryDrawer",&libraryDrawer},{"fileMenu",&fileMenu},{"catalogMenu",&catalogMenu},{"settingsButton",&settingsButton},{"title",&title},{"librarySelector",&librarySelector},{"newLibrary",&newLibrary},{"transportStatus",&transportStatus},{"mix",&mix},{"ref",&ref},
        {"add",&add},{"scan",&scan},{"importCatalog",&importCatalog},{"addUrl",&addUrl},{"remove",&remove},{"relink",&relink},{"recursiveScan",&recursiveScan},{"search",&search},{"favouritesOnly",&favouritesOnly},{"sort",&sort},{"sortDescending",&sortDescending},{"playlist",&playlist},{"newPlaylist",&newPlaylist},{"addToPlaylist",&addToPlaylist},{"previousReference",&previousReference},{"nextReference",&nextReference},{"list",&list},{"mainSplitter",&mainSplitter},
        {"waveform",&waveform},{"play",&play},{"pause",&pause},{"stop",&stop},{"seek",&seek},{"startOffset",&startOffset},{"loopEnabled",&loopEnabled},{"loopStart",&loopStart},{"loopEnd",&loopEnd},{"transportSync",&transportSync},{"syncMode",&syncMode},{"syncOffset",&syncOffset},{"fullLoop",&fullLoop},{"resetWaveformView",&resetWaveformView},{"hostTempoStatus",&hostTempoStatus},
        {"fftSize",&fftSize},{"fftSmoothing",&fftSmoothing},{"analysisSlope",&analysisSlope},{"displayRate",&displayRate},{"freezeDisplay",&freezeDisplay},{"swapLR",&swapLR},{"resetMeters",&resetMeters},{"analysisDisplay",&analysisDisplay},{"analysisMeters",&analysisMeters},
        {"eqCurve",&eqCurve},{"matchBypass",&matchBypass},{"autoMatch",&autoMatch},{"matchMode",&matchMode},{"manualGain",&manualGain},{"matchedGain",&matchedGain},{"eqBypass",&eqBypass},{"listeningMode",&listeningMode},{"showMidSpectrum",&showMidSpectrum},{"showSideSpectrum",&showSideSpectrum},{"fade",&fade},{"hpfEnabled",&hpfEnabled},{"hpf",&hpf},{"hpfSlope",&hpfSlope},{"bellEnabled",&bellEnabled},{"bellFreq",&bellFreq},{"bellGain",&bellGain},{"bellQ",&bellQ},{"lpfEnabled",&lpfEnabled},{"lpf",&lpf},{"lpfSlope",&lpfSlope},{"airwindowsMeter",&airwindowsMeter},
        {"filterArtist",&filterArtist},{"filterGenre",&filterGenre},{"filterKey",&filterKey},{"ratingFilter",&ratingFilter},{"minBpm",&minBpm},{"maxBpm",&maxBpm},{"cacheSize",&cacheSize},{"cacheStatus",&cacheStatus},{"clearCache",&clearCache},{"mixColourSelector",&mixColourSelector},{"referenceColourSelector",&referenceColourSelector},{"editTitle",&editTitle},{"editArtist",&editArtist},{"editAlbum",&editAlbum},{"editGenre",&editGenre},{"editYear",&editYear},{"editBpm",&editBpm},{"editKey",&editKey},{"editRating",&editRating},{"editFavourite",&editFavourite},{"editTags",&editTags},{"editNotes",&editNotes},{"save",&save},{"savePreset",&savePreset},{"loadPreset",&loadPreset},{"safeExport",&safeExport}
    };
    referencelab::createMagicGuiWithComponents(*magicBuilder,magicSurface,[this](const juce::String&id)->juce::Component*{auto found=magicComponents.find(id);return found==magicComponents.end()?nullptr:found->second;});
    magicSurface.setInterceptsMouseClicks(false,true);addAndMakeVisible(magicSurface);applyTheme();resized();
}
ReferenceLabEditor::~ReferenceLabEditor(){if(magicBuilder){referencelab::releaseMagicGuiComponents(*magicBuilder);magicBuilder.reset();}}
void ReferenceLabEditor::refreshLibrary(){referencelab::ReferenceFilter f;f.query=search.getText();f.artist=filterArtist.getText();f.genre=filterGenre.getText();f.musicalKey=filterKey.getText();f.minimumBpm=minBpm.getText().isEmpty()?0:minBpm.getText().getDoubleValue();f.maximumBpm=maxBpm.getText().isEmpty()?999:maxBpm.getText().getDoubleValue();f.minimumRating=juce::jmax(0,ratingFilter.getSelectedId()-1);f.favouritesOnly=favouritesOnly.getToggleState();f.sort=static_cast<referencelab::ReferenceSort>(juce::jmax(0,sort.getSelectedId()-1));f.ascending=!sortDescending.getToggleState();rows=p.getReferenceManager().filter(f);list.updateContent();list.repaint();}
void ReferenceLabEditor::refreshPlaylists(){auto selected=playlist.getText();playlistRows=p.getReferenceManager().playlistsSnapshot();playlist.clear(juce::dontSendNotification);for(size_t i=0;i<playlistRows.size();++i)playlist.addItem(playlistRows[i].name+" ("+juce::String(playlistRows[i].referenceIds.size())+")",(int)i+1);for(size_t i=0;i<playlistRows.size();++i)if(playlistRows[i].name==selected.upToFirstOccurrenceOf(" (",false,false)){playlist.setSelectedItemIndex((int)i,juce::dontSendNotification);return;}if(!playlistRows.empty())playlist.setSelectedItemIndex(0,juce::dontSendNotification);}
void ReferenceLabEditor::refreshLibraries(){libraryRows=p.getReferenceManager().librariesSnapshot();librarySelector.clear(juce::dontSendNotification);auto active=p.getReferenceManager().activeLibraryId();for(size_t i=0;i<libraryRows.size();++i){librarySelector.addItem(libraryRows[i].name,(int)i+1);if(libraryRows[i].id==active)librarySelector.setSelectedItemIndex((int)i,juce::dontSendNotification);}}
void ReferenceLabEditor::showError(const juce::String&e){juce::NativeMessageBox::showMessageBoxAsync(juce::MessageBoxIconType::WarningIcon,"ReferenceLab",e);}
void ReferenceLabEditor::chooseFolder(){auto chooser=std::make_shared<juce::FileChooser>("Cartella reference");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectDirectories,[this,chooser](const juce::FileChooser&f){if(f.getResult().isDirectory()){juce::String warning;p.getReferenceManager().scanFolder(f.getResult(),recursiveScan.getToggleState(),warning);if(warning.isNotEmpty())showError(warning);refreshLibrary();}});}
void ReferenceLabEditor::chooseCatalog(){auto chooser=std::make_shared<juce::FileChooser>("Importa catalogo JSON",juce::File{},"*.json");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this,chooser](const juce::FileChooser&f){if(f.getResult().existsAsFile()){juce::String warning;auto added=p.getReferenceManager().importCatalog(f.getResult(),warning);if(warning.isNotEmpty())showError(warning);else if(added==0)showError("Il catalogo non contiene nuove reference");refreshLibrary();}});}
void ReferenceLabEditor::paintListBoxItem(int row,juce::Graphics&g,int w,int h,bool selected){if(row<0||row>=getNumRows())return;if(selected)g.fillAll(juce::Colour(0xff315b78));auto&item=rows[(size_t)row];auto remote=item.source.startsWithIgnoreCase("http://")||item.source.startsWithIgnoreCase("https://");auto lib=p.getReferenceManager().snapshot();auto file=item.resolveAgainst(lib.root);auto state=p.getCacheManager().getState(file);juce::String badge=remote?"[WEB] ":state==referencelab::CacheState::cached?"[CACHE] ":state==referencelab::CacheState::loading?"[LOAD] ":state==referencelab::CacheState::error?"[ERR] ":"";g.setColour(remote||file.existsAsFile()?juce::Colours::white:juce::Colours::orangered);g.drawText(badge+item.title+"  -  "+item.artist,10,0,w-20,h,juce::Justification::centredLeft,true);}
void ReferenceLabEditor::listBoxItemDoubleClicked(int row,const juce::MouseEvent&){if(row<0||row>=getNumRows())return;configurePlayback(row);playItem(rows[(size_t)row]);}
void ReferenceLabEditor::playItem(const referencelab::ReferenceMetadata&item){p.getPlayer().setStartOffset(item.startOffsetSeconds);p.getPlayer().setLoop(item.loop.enabled,item.loop.startSeconds,item.loop.endSeconds,item.loop.crossfadeMs);waveform.setLoop(item.loop.enabled,item.loop.startSeconds,item.loop.endSeconds);auto remote=item.source.startsWithIgnoreCase("http://")||item.source.startsWithIgnoreCase("https://");auto file=item.resolveAgainst(p.getReferenceManager().snapshot().root);juce::Component::SafePointer<ReferenceLabEditor>safe(this);auto completed=[safe](const juce::String&error){if(!safe)return;if(error.isNotEmpty())safe->showError(error);else{safe->p.setReference(true);safe->waveform.resetView();}safe->list.repaint();};if(remote)p.loadUrlAsync(juce::URL(item.source),std::move(completed));else p.loadFileAsync(file,std::move(completed));list.repaint();}
void ReferenceLabEditor::selectedRowsChanged(int row){if(row<0||row>=getNumRows())return;auto&m=rows[(size_t)row];editTitle.setText(m.title,false);editArtist.setText(m.artist,false);editAlbum.setText(m.album,false);editGenre.setText(m.genre,false);editYear.setText(m.year?juce::String(*m.year):juce::String{},false);editBpm.setText(m.bpm?juce::String(*m.bpm,2):juce::String{},false);editKey.setText(m.musicalKey,false);editRating.setText(m.rating?juce::String(*m.rating):juce::String{},false);editTags.setText(m.tags.joinIntoString(", "),false);editNotes.setText(m.notes,false);editFavourite.setToggleState(m.favourite,juce::dontSendNotification);const double duration=juce::jmax(1.0,m.durationSeconds);for(auto*s:{&seek,&startOffset,&loopStart,&loopEnd})s->setRange(0.0,duration,.01);startOffset.setValue(m.startOffsetSeconds,juce::dontSendNotification);loopStart.setValue(m.loop.startSeconds,juce::dontSendNotification);loopEnd.setValue(m.loop.endSeconds,juce::dontSendNotification);loopEnabled.setToggleState(m.loop.enabled,juce::dontSendNotification);}
void ReferenceLabEditor::configurePlayback(int row){if(row<0||row>=getNumRows())return;auto&m=rows[(size_t)row];p.getPlayer().setStartOffset(m.startOffsetSeconds);p.getPlayer().setLoop(m.loop.enabled,m.loop.startSeconds,m.loop.endSeconds,m.loop.crossfadeMs);waveform.setLoop(m.loop.enabled,m.loop.startSeconds,m.loop.endSeconds);}
void ReferenceLabEditor::applyLoop(){p.getPlayer().setLoop(loopEnabled.getToggleState(),loopStart.getValue(),loopEnd.getValue());waveform.setLoop(loopEnabled.getToggleState(),loopStart.getValue(),loopEnd.getValue());}
void ReferenceLabEditor::persistPlayback(){auto row=list.getSelectedRow();if(row<0||row>=getNumRows())return;auto item=rows[(size_t)row];item.startOffsetSeconds=startOffset.getValue();item.loop.enabled=loopEnabled.getToggleState();item.loop.startSeconds=loopStart.getValue();item.loop.endSeconds=loopEnd.getValue();if(item.loop.enabled&&!item.loop.isValid()){showError("Il marker B deve essere successivo al marker A");return;}juce::String error;if(!p.getReferenceManager().updateMetadata(item,error))showError(error);else rows[(size_t)row]=std::move(item);}
void ReferenceLabEditor::saveSelected(){const int row=list.getSelectedRow();if(row<0||row>=getNumRows())return;auto item=rows[(size_t)row];item.title=editTitle.getText().trim();item.artist=editArtist.getText().trim();item.album=editAlbum.getText().trim();item.genre=editGenre.getText().trim();item.musicalKey=editKey.getText().trim();item.notes=editNotes.getText();item.favourite=editFavourite.getToggleState();item.tags=juce::StringArray::fromTokens(editTags.getText(),",","\"");item.tags.trim();item.tags.removeEmptyStrings();const auto bpm=editBpm.getText().trim();const auto year=editYear.getText().trim();const auto rating=editRating.getText().trim();item.bpm=bpm.isEmpty()?std::nullopt:std::optional<double>(bpm.getDoubleValue());item.year=year.isEmpty()?std::nullopt:std::optional<int>(year.getIntValue());item.rating=rating.isEmpty()?std::nullopt:std::optional<int>(rating.getIntValue());juce::String error;if(!p.getReferenceManager().updateMetadata(item,error))showError(error);refreshLibrary();}
void ReferenceLabEditor::removeSelected(){auto row=list.getSelectedRow();if(row<0||row>=getNumRows())return;juce::String error;if(!p.getReferenceManager().remove(rows[(size_t)row].uuid,error))showError(error);refreshLibrary();}
void ReferenceLabEditor::updateSourceStatus(){auto referenceSelected=p.isReference();auto loaded=p.getPlayer().isLoaded();auto playing=loaded&&p.getPlayer().isPlaying();auto toggle=[](juce::Button&button,bool value){if(button.getToggleState()!=value)button.setToggleState(value,juce::dontSendNotification);};auto caption=[](juce::Button&button,const juce::String&value){if(button.getButtonText()!=value)button.setButtonText(value);};toggle(mix,!referenceSelected);toggle(ref,referenceSelected);toggle(play,playing);caption(mix,referenceSelected?"MIX":"> MIX");caption(ref,referenceSelected?"> REFERENCE":"REFERENCE");juce::String status=referenceSelected?"REF":"MIX";auto remote=p.getRemoteLoadState();if(remote==ReferenceLabAudioProcessor::RemoteLoadState::downloading)status+=" | WEB "+juce::String(juce::roundToInt(p.getRemoteLoadProgress()*100))+"%";else if(remote==ReferenceLabAudioProcessor::RemoteLoadState::decoding)status+=" | DECODIFICA";else if(remote==ReferenceLabAudioProcessor::RemoteLoadState::error)status+=" | WEB ERRORE";else{if(referenceSelected)status+=!loaded?" | NON CARICATA":playing?" | PLAY":" | PAUSA";if(remote==ReferenceLabAudioProcessor::RemoteLoadState::ready)status+=" | WEB";status+=transportSync.getToggleState()?(p.isTransportAvailable()?" | DAW SYNC":" | SYNC N/A"):" | FREE";}auto colour=referenceSelected?appliedReferenceColour:appliedMixColour;if(transportStatus.findColour(juce::Label::textColourId)!=colour)transportStatus.setColour(juce::Label::textColourId,colour);if(transportStatus.getText()!=status)transportStatus.setText(status,juce::dontSendNotification);auto hostPosition=p.getHostPositionSeconds();juce::String host=hostPosition>=0.0?(p.isHostPlaying()?"HOST PLAY":"HOST STOP"):"HOST TRANSPORT N/A";if(p.getHostBpm()>0.0)host+=" | "+juce::String(p.getHostBpm(),1)+" BPM";auto numerator=p.getHostTimeSignatureNumerator(),denominator=p.getHostTimeSignatureDenominator();if(numerator>0&&denominator>0)host+=" | "+juce::String(numerator)+"/"+juce::String(denominator);if(hostPosition>=0.0)host+=" | "+juce::String(hostPosition,1)+" s";if(hostTempoStatus.getText()!=host)hostTempoStatus.setText(host,juce::dontSendNotification);}
void ReferenceLabEditor::updateCacheStatus(){constexpr std::size_t bytesPerMb=1024u*1024u;auto choice=cacheChoiceFor((int)p.state.state.getProperty("uiCacheMb",512));auto desiredMb=cacheSizesMb[choice-1];auto desiredBytes=(std::size_t)desiredMb*bytesPerMb;if(p.getCacheManager().getMaximumBytes()!=desiredBytes)p.getCacheManager().setMaximumBytes(desiredBytes);if(cacheSize.getSelectedId()!=choice)cacheSize.setSelectedId(choice,juce::dontSendNotification);auto used=(double)p.getCacheManager().getCurrentBytes()/(double)bytesPerMb;auto status="RAM "+juce::String(used,1)+" / "+juce::String(desiredMb)+" MB";if(cacheStatus.getText()!=status)cacheStatus.setText(status,juce::dontSendNotification);}
void ReferenceLabEditor::timerCallback()
{
    eqCurve.setSampleRate(p.getSampleRate());
    if(appliedMixColour!=referencelab::UiTheme::mix(p.state.state)||appliedReferenceColour!=referencelab::UiTheme::reference(p.state.state))applyTheme();
    updateSourceStatus();updateCacheStatus();
    analysisDisplay.setReferenceSelected(p.isReference());eqCurve.setReferenceSelected(p.isReference());
    eqCurve.setReferenceAvailable(p.getPlayer().isLoaded());
    analysisMeters.setSnapshots(p.getMixMeters(),p.getReferenceMeters(),p.getOutputMeters());
    matchedGain.setText("Applied "+juce::String(p.getMatchedGainDb(),1)+" dB",juce::dontSendNotification);
    const auto duration=juce::jmax(1.0,p.getPlayer().getDurationSeconds());if(std::abs(seek.getMaximum()-duration)>.01){for(auto*s:{&seek,&startOffset,&loopStart,&loopEnd})s->setRange(0.0,duration,.01);}
    if(!seek.isMouseButtonDown())seek.setValue(p.getPlayer().getPositionSeconds(),juce::dontSendNotification);
    const auto magicTab=juce::jlimit(0,3,(int)p.getGuiState().getPropertyAsValue("uiTab").getValue());
    if((int)p.state.state.getProperty("uiTab",0)!=magicTab)p.state.state.setProperty("uiTab",magicTab,nullptr);
    list.repaint();
}
void ReferenceLabEditor::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff10151d));}
void ReferenceLabEditor::applyTheme(){auto mixColour=referencelab::UiTheme::mix(p.state.state);auto referenceColour=referencelab::UiTheme::reference(p.state.state);appliedMixColour=mixColour;appliedReferenceColour=referenceColour;referencelab::setGuiMagicSourceColours(p.getGuiState().getGuiTree(),mixColour,referenceColour);magicBuilder->updateColours();mixColourSelector.setSelectedId(referencelab::UiTheme::paletteId(mixColour),juce::dontSendNotification);referenceColourSelector.setSelectedId(referencelab::UiTheme::paletteId(referenceColour),juce::dontSendNotification);waveform.setReferenceColour(referenceColour);analysisMeters.setSourceColours(mixColour,referenceColour);airwindowsMeter.setSourceColours(mixColour,referenceColour);mix.setColour(juce::TextButton::buttonColourId,mixColour.darker(.75f));mix.setColour(juce::TextButton::buttonOnColourId,mixColour);ref.setColour(juce::TextButton::buttonColourId,referenceColour.darker(.75f));ref.setColour(juce::TextButton::buttonOnColourId,referenceColour);mixColourSelector.setColour(juce::ComboBox::backgroundColourId,mixColour.darker(.75f));referenceColourSelector.setColour(juce::ComboBox::backgroundColourId,referenceColour.darker(.75f));updateSourceStatus();analysisDisplay.repaint();eqCurve.repaint();repaint();}
bool ReferenceLabEditor::keyPressed(const juce::KeyPress&key){if(key.getTextCharacter()=='b'||key.getTextCharacter()=='B'){p.setReference(!p.isReference());return true;}if(key==juce::KeyPress::spaceKey){p.getPlayer().isPlaying()?p.pauseReference():p.playReference();return true;}return false;}
void ReferenceLabEditor::resized(){
    p.state.state.setProperty("uiWidth",getWidth(),nullptr);p.state.state.setProperty("uiHeight",getHeight(),nullptr);
    magicSurface.setBounds(getLocalBounds());magicBuilder->updateLayout(magicSurface.getLocalBounds());
}
